In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../metanet/data/trimmed/Example.csv")

In [16]:
df

,name,hasAnnotation,hasSentence,Example.Construction,label,comment
0,Example_3011,['chained by debt'],"['a consumer chained by debt', 'If you', 'wher...",['Passive-Verb(S) by Noun(T)'],"['If you, like the average American,...']",NaN
1,Example_2610,['government has catered'],['Alberta Premier Rachel Notley responds to cl...,['Subject(T) Verb(S)'],['Alberta Premier Rachel Notley responds...'],NaN
2,Example_4732,['handed an education'],"['I resented them a little', 'until I watched ...",['Verb(S) Direct Object(T)'],"['I resented them a little, until...']",NaN
3,Example_4724,['income fell'],"['892 in 2009.', 'Their average income fell to...",['Subject(T) Verb(S)'],"['Their average income fell to $992,892...']",NaN
4,Example_2566,['government can cure'],['Nahendeh MLA Shane Thompson has a suggestion...,['Subject(T) Verb(S)'],['Nahendeh MLA Shane Thompson has...'],NaN
...,...,...,...,...,...,...
5605,Example_4220,NaN,['I hope and pray that everyone will try to un...,NaN,['I hope and pray that everyone will...'],['past is behind me']
5606,Example_197,['treat poverty'],['Treat poverty as an “underlying condition”.'],['Verb(S) Direct Object(T)'],['Treat poverty as an “underlying...'],NaN
5607,Example_3052,NaN,['They told us that lack of bus fare is holdin...,NaN,['They told us that lack of bus fare...'],['holding them back from accessing education']
5608,Example_5539,['money handed over'],['Councillors previously set four conditions t...,['Subject(T) Verb(S)'],['Councillors previously set four...'],NaN
5609,Example_987,NaN,['Clear skies ahead for Metro Vancouver’s hous...,NaN,['Clear skies ahead for Metro Vancouver’s...'],NaN

In [17]:
df = df[['name', 'hasSentence', 'Example.Construction']]

df = df.dropna()

In [18]:
df

,name,hasSentence,Example.Construction
0,Example_3011,"['a consumer chained by debt', 'If you', 'wher...",['Passive-Verb(S) by Noun(T)']
1,Example_2610,['Alberta Premier Rachel Notley responds to cl...,['Subject(T) Verb(S)']
2,Example_4732,"['I resented them a little', 'until I watched ...",['Verb(S) Direct Object(T)']
3,Example_4724,"['892 in 2009.', 'Their average income fell to...",['Subject(T) Verb(S)']
4,Example_2566,['Nahendeh MLA Shane Thompson has a suggestion...,['Subject(T) Verb(S)']
...,...,...,...
5601,Example_2272,['The musicians who performed the concert also...,['Adjective(S) Noun(T)']
5602,Example_1629,"['If you are here', 'seemingly big or small.',...","[""Noun's(T) Noun(S)""]"
5604,Example_5085,['While maintaining that there is no such thin...,['Subject(T) Verb(S)']
5606,Example_197,['Treat poverty as an “underlying condition”.'],['Verb(S) Direct Object(T)']
5608,Example_5539,['Councillors previously set four conditions t...,['Subject(T) Verb(S)']

In [19]:
import ast

df['Example.Construction'] = df['Example.Construction'].apply(lambda x: ast.literal_eval(x)[0])

In [20]:
df['Example.Construction'].value_counts()

Example.Construction
Verb(S) Direct Object(T)              837
Subject(T) Verb(S)                    712
Verb(S) preposition Noun(T)           517
Noun(S) of Noun(T)                    501
Adjective(S) Noun(T)                  493
Noun(S) preposition Noun(T)           228
Adjective(T) Noun(S)                  174
Noun(T) Noun(S) Compound              158
Noun(T) copula Noun(S)                149
Noun's(T) Noun(S)                      98
Noun(T) copula Adjective(S)            65
Passive-Verb(S) by Noun(T)             28
Noun(T) copula preposition Noun(S)     24
Name: count, dtype: int64

In [21]:
df

,name,hasSentence,Example.Construction
0,Example_3011,"['a consumer chained by debt', 'If you', 'wher...",Passive-Verb(S) by Noun(T)
1,Example_2610,['Alberta Premier Rachel Notley responds to cl...,Subject(T) Verb(S)
2,Example_4732,"['I resented them a little', 'until I watched ...",Verb(S) Direct Object(T)
3,Example_4724,"['892 in 2009.', 'Their average income fell to...",Subject(T) Verb(S)
4,Example_2566,['Nahendeh MLA Shane Thompson has a suggestion...,Subject(T) Verb(S)
...,...,...,...
5601,Example_2272,['The musicians who performed the concert also...,Adjective(S) Noun(T)
5602,Example_1629,"['If you are here', 'seemingly big or small.',...",Noun's(T) Noun(S)
5604,Example_5085,['While maintaining that there is no such thin...,Subject(T) Verb(S)
5606,Example_197,['Treat poverty as an “underlying condition”.'],Verb(S) Direct Object(T)
5608,Example_5539,['Councillors previously set four conditions t...,Subject(T) Verb(S)

In [22]:
import json

with open("data/primary_examples.json") as f:
    all_examples = json.load(f)

all_examples

['Example_1700',
 'Example_1701',
 'Example_1705',
 'Example_1704',
 'Example_1702',
 'Example_1703',
 'Example_136',
 'Example_134',
 'Example_132',
 'Example_135',
 'Example_131',
 'Example_133',
 'Example_137',
 'Example_108',
 'Example_115',
 'Example_107',
 'Example_109',
 'Example_111',
 'Example_113',
 'Example_112',
 'Example_110',
 'Example_114',
 'Example_647',
 'Example_649',
 'Example_650',
 'Example_648',
 'Example_646',
 'Example_651',
 'Example_1124',
 'Example_1117',
 'Example_1121',
 'Example_1119',
 'Example_1118',
 'Example_1122',
 'Example_1123',
 'Example_1120',
 'Example_1824',
 'Example_1827',
 'Example_1826',
 'Example_1825',
 'Example_1823',
 'Example_1822',
 'Example_5011',
 'Example_5013',
 'Example_5016',
 'Example_5015',
 'Example_5012',
 'Example_5014',
 'Example_1642',
 'Example_1641',
 'Example_1645',
 'Example_1644',
 'Example_1643',
 'Example_1639',
 'Example_1640',
 'Example_1646',
 'Example_2982',
 'Example_2980',
 'Example_2978',
 'Example_2977',
 'Example_2981',
 'Example_2979',
 'Example_5604',
 'Example_5602',
 'Example_5596',
 'Example_5599',
 'Example_5603',
 'Example_5600',
 'Example_5598',
 'Example_5601',
 'Example_5597',
 'Example_4161',
 'Example_4159',
 'Example_4165',
 'Example_4160',
 'Example_4163',
 'Example_4162',
 'Example_4164',
 'Example_5313',
 'Example_5314',
 'Example_5308',
 'Example_5312',
 'Example_5311',
 'Example_5309',
 'Example_5310',
 'Example_4712',
 'Example_4705',
 'Example_4710',
 'Example_4709',
 'Example_4711',
 'Example_4707',
 'Example_4706',
 'Example_4708',
 'Example_5485',
 'Example_5492',
 'Example_5490',
 'Example_5491',
 'Example_5486',
 'Example_5487',
 'Example_5489',
 'Example_5488',
 'Example_482',
 'Example_480',
 'Example_484',
 'Example_479',
 'Example_485',
 'Example_483',
 'Example_481',
 'Example_486',
 'Example_3075',
 'Example_3077',
 'Example_3081',
 'Example_3076',
 'Example_3080',
 'Example_3078',
 'Example_3079',
 'Example_2007',
 'Example_2001',
 'Example_2006',
 'Example_2008',
 'Example_2003',
 'Example_2005',
 'Example_2002',
 'Example_2000',
 'Example_2004',
 'Example_5302',
 'Example_5301',
 'Example_5303',
 'Example_5304',
 'Example_5305',
 'Example_5307',
 'Example_5306',
 'Example_5300',
 'Example_2019',
 'Example_2017',
 'Example_2022',
 'Example_2016',
 'Example_2018',
 'Example_2021',
 'Example_2020',
 'Example_2015',
 'Example_2835',
 'Example_2832',
 'Example_2836',
 'Example_2834',
 'Example_2831',
 'Example_2833',
 'Example_4220',
 'Example_4223',
 'Example_4224',
 'Example_4225',
 'Example_4222',
 'Example_4221',
 'Example_814',
 'Example_817',
 'Example_818',
 'Example_816',
 'Example_815',
 'Example_813',
 'Example_240',
 'Example_242',
 'Example_243',
 'Example_245',
 'Example_244',
 'Example_241',
 'Example_5124',
 'Example_5125',
 'Example_5126',
 'Example_5128',
 'Example_5127',
 'Example_5129',
 'Example_5455',
 'Example_5454',
 'Example_5449',
 'Example_5450',
 'Example_5453',
 'Example_5452',
 'Example_5451',
 'Example_440',
 'Example_435',
 'Example_438',
 'Example_441',
 'Example_437',
 'Example_436',
 'Example_439',
 'Example_870',
 'Example_871',
 'Example_868',
 'Example_866',
 'Example_865',
 'Example_872',
 'Example_864',
 'Example_867',
 'Example_869',
 'Example_2088',
 'Example_2084',
 'Example_2085',
 'Example_2089',
 'Example_2087',
 'Example_2086',
 'Example_3794',
 'Example_3797',
 'Example_3793',
 'Example_3799',
 'Example_3798',
 'Example_3795',
 'Example_3796',
 'Example_495',
 'Example_496',
 'Example_494',
 'Example_497',
 'Example_501',
 'Example_499',
 'Example_498',
 'Example_500',
 'Example_1551',
 'Example_1553',
 'Example_1550',
 'Example_1552',
 'Example_1545',
 'Example_1548',
 'Example_1549',
 'Example_1546',
 'Example_1547',
 'Example_4489',
 'Example_4492',
 'Example_4488',
 'Example_4490',
 'Example_4491',
 'Example_4487',
 'Example_5563',
 'Example_5567',
 'Example_5561',
 'Example_5565',
 'Example_5564',
 'Example_5566',
 'Example_5562',
 'Example_5360',
 'Example_5359',
 'Example_5365',
 'Example_5364',
 'Example_5358',
 'Example_5357',
 'Example_5363',
 'Example_5366',
 'Example_5361',
 'Example_5362',
 'Example_564',
 'Example_567',
 'Example_566',
 'Example_565',
 'Example_569',
 'Example_568',
 'Example_2119',
 'Example_2116',
 'Example_2120',
 'Example_2115',
 'Example_2117',
 'Example_2125',
 'Example_2121',
 'Example_2123',
 'Example_2124',
 'Example_2118',
 'Example_2114',
 'Example_2122',
 'Example_4123',
 'Example_4124',
 'Example_4125',
 'Example_4121',
 'Example_4119',
 'Example_4120',
 'Example_4122',
 'Example_4938',
 'Example_4937',
 'Example_4941',
 'Example_4942',
 'Example_4940',
 'Example_4939',
 'Example_4943',
 'Example_4136',
 'Example_4132',
 'Example_4134',
 'Example_4135',
 'Example_4137',
 'Example_4133',
 'Example_5400',
 'Example_5401',
 'Example_5405',
 'Example_5404',
 'Example_5403',
 'Example_5399',
 'Example_5402',
 'Example_1924',
 'Example_1929',
 'Example_1928',
 'Example_1921',
 'Example_1927',
 'Example_1926',
 'Example_1922',
 'Example_1925',
 'Example_1923',
 'Example_4384',
 'Example_4386',
 'Example_4383',
 'Example_4388',
 'Example_4385',
 'Example_4387',
 'Example_5333',
 'Example_5330',
 'Example_5334',
 'Example_5336',
 'Example_5332',
 'Example_5331',
 'Example_5337',
 'Example_5335',
 'Example_5339',
 'Example_5338',
 'Example_5471',
 'Example_5467',
 'Example_5466',
 'Example_5470',
 'Example_5464',
 'Example_5468',
 'Example_5465',
 'Example_5469',
 'Example_2232',
 'Example_2231',
 'Example_2235',
 'Example_2236',
 'Example_2233',
 'Example_2234',
 'Example_5545',
 'Example_5542',
 'Example_5540',
 'Example_5544',
 'Example_5541',
 'Example_5543',
 'Example_5546',
 'Example_1479',
 'Example_1483',
 'Example_1482',
 'Example_1481',
 'Example_1484',
 'Example_1478',
 'Example_1480',
 'Example_506',
 'Example_503',
 'Example_504',
 'Example_505',
 'Example_507',
 'Example_502',
 'Example_508',
 'Example_3248',
 'Example_3247',
 'Example_3242',
 'Example_3244',
 'Example_3246',
 'Example_3241',
 'Example_3243',
 'Example_3245',
 'Example_3249',
 'Example_1915',
 'Example_1918',
 'Example_1920',
 'Example_1917',
 'Example_1919',
 'Example_1914',
 'Example_1916',
 'Example_2894',
 'Example_2897',
 'Example_2898',
 'Example_2893',
 'Example_2895',
 'Example_2896',
 'Example_4651',
 'Example_4655',
 'Example_4650',
 'Example_4652',
 'Example_4653',
 'Example_4654',
 'Example_1370',
 'Example_1374',
 'Example_1371',
 'Example_1372',
 'Example_1373',
 'Example_1369',
 'Example_4139',
 'Example_4143',
 'Example_4138',
 'Example_4140',
 'Example_4141',
 'Example_4144',
 'Example_4142',
 'Example_5377',
 'Example_5382',
 'Example_5379',
 'Example_5380',
 'Example_5375',
 'Example_5378',
 'Example_5381',
 'Example_5376',
 'Example_658',
 'Example_653',
 'Example_656',
 'Example_652',
 'Example_655',
 'Example_654',
 'Example_657',
 'Example_548',
 'Example_549',
 'Example_547',
 'Example_550',
 'Example_544',
 'Example_545',
 'Example_546',
 'Example_4975',
 'Example_4974',
 'Example_4976',
 'Example_4972',
 'Example_4973',
 'Example_4977',
 'Example_3324',
 'Example_3323',
 'Example_3321',
 'Example_3326',
 'Example_3325',
 'Example_3322',
 'Example_3320',
 'Example_938',
 'Example_941',
 'Example_940',
 'Example_942',
 'Example_939',
 'Example_937',
 'Example_4821',
 'Example_4822',
 'Example_4817',
 'Example_4820',
 'Example_4819',
 'Example_4818',
 'Example_2040',
 'Example_2036',
 'Example_2042',
 'Example_2041',
 'Example_2037',
 'Example_2035',
 'Example_2039',
 'Example_2038',
 'Example_419',
 'Example_420',
 'Example_413',
 'Example_414',
 'Example_418',
 'Example_416',
 'Example_417',
 'Example_415',
 'Example_487',
 'Example_488',
 'Example_491',
 'Example_490',
 'Example_493',
 'Example_489',
 'Example_492',
 'Example_2687',
 'Example_2690',
 'Example_2689',
 'Example_2686',
 'Example_2691',
 'Example_2688',
 'Example_2692',
 'Example_5121',
 'Example_5122',
 'Example_5120',
 'Example_5123',
 'Example_5119',
 'Example_5118',
 'Example_5572',
 'Example_5573',
 'Example_5570',
 'Example_5574',
 'Example_5569',
 'Example_5568',
 'Example_5575',
 'Example_5571',
 'Example_948',
 'Example_945',
 'Example_949',
 'Example_946',
 'Example_943',
 'Example_944',
 'Example_947',
 'Example_1634',
 'Example_1636',
 'Example_1633',
 'Example_1635',
 'Example_1632',
 'Example_1637',
 'Example_1638',
 'Example_5190',
 'Example_5188',
 'Example_5189',
 'Example_5187',
 'Example_5185',
 'Example_5186',
 'Example_5184',
 'Example_141',
 'Example_140',
 'Example_138',
 'Example_143',
 'Example_144',
 'Example_142',
 'Example_139',
 'Example_145',
 'Example_3071',
 'Example_3067',
 'Example_3068',
 'Example_3070',
 'Example_3074',
 'Example_3073',
 'Example_3069',
 'Example_3072',
 'Example_4198',
 'Example_4190',
 'Example_4194',
 'Example_4191',
 'Example_4192',
 'Example_4197',
 'Example_4195',
 'Example_4196',
 'Example_4193',
 'Example_4766',
 'Example_4764',
 'Example_4768',
 'Example_4767',
 'Example_4765',
 'Example_4769',
 'Example_4763',
 'Example_3387',
 'Example_3382',
 'Example_3386',
 'Example_3385',
 'Example_3380',
 'Example_3379',
 'Example_3381',
 'Example_3383',
 'Example_3384',
 'Example_4985',
 'Example_4989',
 'Example_4987',
 'Example_4988',
 'Example_4990',
 'Example_4986',
 'Example_4995',
 'Example_4996',
 'Example_4998',
 'Example_4994',
 'Example_4993',
 'Example_4991',
 'Example_4992',
 'Example_4997',
 'Example_2185',
 'Example_2184',
 'Example_2187',
 'Example_2182',
 'Example_2180',
 'Example_2181',
 'Example_2186',
 'Example_2183',
 'Example_985',
 'Example_988',
 'Example_987',
 'Example_986',
 'Example_984',
 'Example_990',
 'Example_989',
 'Example_4228',
 'Example_4230',
 'Example_4226',
 'Example_4231',
 'Example_4227',
 'Example_4229',
 'Example_4154',
 'Example_4157',
 'Example_4152',
 'Example_4153',
 'Example_4155',
 'Example_4158',
 'Example_4151',
 'Example_4156',
 'Example_1189',
 'Example_1191',
 'Example_1185',
 'Example_1190',
 'Example_1187',
 'Example_1188',
 'Example_1186',
 'Example_2863',
 'Example_2864',
 'Example_2866',
 'Example_2862',
 'Example_2865',
 'Example_2861',
 'Example_125',
 'Example_128',
 'Example_130',
 'Example_129',
 'Example_127',
 'Example_122',
 'Example_126',
 'Example_124',
 'Example_123',
 'Example_3751',
 'Example_3747',
 'Example_3750',
 'Example_3749',
 'Example_3746',
 'Example_3748',
 'Example_5327',
 'Example_5326',
 'Example_5328',
 'Example_5324',
 'Example_5329',
 'Example_5325',
 'Example_5323',
 'Example_5322',
 'Example_1905',
 'Example_1911',
 'Example_1913',
 'Example_1907',
 'Example_1910',
 'Example_1906',
 'Example_1909',
 'Example_1908',
 'Example_1912',
 'Example_5483',
 'Example_5484',
 'Example_5480',
 'Example_5482',
 'Example_5478',
 'Example_5481',
 'Example_5479',
 'Example_2678',
 'Example_2685',
 'Example_2683',
 'Example_2679',
 'Example_2684',
 'Example_2682',
 'Example_2680',
 'Example_2681',
 'Example_517',
 'Example_2130',
 'Example_2128',
 'Example_2127',
 'Example_2129',
 'Example_2131',
 'Example_2126',
 'Example_2899',
 'Example_2901',
 'Example_2903',
 'Example_2902',
 'Example_2905',
 'Example_2900',
 'Example_2904',
 'Example_164',
 'Example_165',
 'Example_168',
 'Example_167',
 'Example_169',
 'Example_166',
 'Example_4720',
 'Example_4718',
 'Example_4715',
 'Example_4716',
 'Example_4713',
 'Example_4719',
 'Example_4717',
 'Example_4714',
 'Example_1177',
 'Example_1172',
 'Example_1176',
 'Example_1173',
 'Example_1174',
 'Example_1175',
 'Example_465',
 'Example_471',
 'Example_467',
 'Example_469',
 'Example_470',
 'Example_466',
 'Example_464',
 'Example_463',
 'Example_468',
 'Example_3389',
 'Example_3390',
 'Example_3393',
 'Example_3395',
 'Example_3391',
 'Example_3392',
 'Example_3388',
 'Example_3394',
 'Example_4099',
 'Example_4097',
 'Example_4098',
 'Example_4095',
 'Example_4100',
 'Example_4096',
 'Example_3065',
 'Example_3063',
 'Example_3061',
 'Example_3066',
 'Example_3064',
 'Example_3062',
 'Example_1280',
 'Example_1278',
 'Example_1283',
 'Example_1281',
 'Example_1284',
 'Example_1285',
 'Example_1282',
 'Example_1279',
 'Example_1071',
 'Example_1072',
 'Example_1074',
 'Example_1070',
 'Example_1069',
 'Example_1073',
 'Example_2870',
 'Example_2867',
 'Example_2869',
 'Example_2874',
 'Example_2868',
 'Example_2871',
 'Example_2872',
 'Example_2875',
 'Example_2873',
 'Example_978',
 'Example_979',
 'Example_981',
 'Example_977',
 'Example_983',
 'Example_980',
 'Example_982',
 'Example_3908',
 'Example_3906',
 'Example_3909',
 'Example_3905',
 'Example_3907',
 'Example_3910',
 'Example_4823',
 'Example_4827',
 'Example_4824',
 'Example_4828',
 'Example_4826',
 'Example_4825',
 'Example_1165',
 'Example_1164',
 'Example_1162',
 'Example_1161',
 'Example_1163',
 'Example_1159',
 'Example_1160',
 'Example_927',
 'Example_924',
 'Example_926',
 'Example_921',
 'Example_920',
 'Example_925',
 'Example_923',
 'Example_922',
 'Example_4728',
 'Example_4721',
 'Example_4724',
 'Example_4722',
 'Example_4726',
 'Example_4727',
 'Example_4725',
 'Example_4723',
 'Example_4684',
 'Example_4682',
 'Example_4683',
 'Example_4681',
 'Example_4685',
 'Example_4686',
 'Example_1086',
 'Example_1083',
 'Example_1087',
 'Example_1084',
 'Example_1089',
 'Example_1088',
 'Example_1085',
 'Example_4796',
 'Example_4801',
 'Example_4798',
 'Example_4794',
 'Example_4800',
 'Example_4795',
 'Example_4799',
 'Example_4797',
 'Example_159',
 'Example_161',
 'Example_158',
 'Example_160',
 'Example_162',
 'Example_163',
 'Example_5141',
 'Example_5146',
 'Example_5139',
 'Example_5142',
 'Example_5145',
 'Example_5138',
 'Example_5144',
 'Example_5143',
 'Example_5147',
 'Example_5140',
 'Example_2077',
 'Example_2081',
 'Example_2079',
 'Example_2083',
 'Example_2078',
 'Example_2082',
 'Example_2080',
 'Example_1211',
 'Example_1207',
 'Example_1214',
 'Example_1206',
 'Example_1210',
 'Example_1208',
 'Example_1205',
 'Example_1209',
 'Example_1213',
 'Example_1212',
 'Example_726',
 'Example_728',
 'Example_729',
 'Example_730',
 'Example_727',
 'Example_731',
 'Example_732',
 'Example_3573',
 'Example_3577',
 'Example_3574',
 'Example_3575',
 'Example_3578',
 'Example_3576',
 'Example_1064',
 'Example_1066',
 'Example_1062',
 'Example_1065',
 'Example_1060',
 'Example_1061',
 'Example_1067',
 'Example_1063',
 'Example_1068',
 'Example_4218',
 'Example_4216',
 'Example_4214',
 'Example_4215',
 'Example_4219',
 'Example_4217',
 'Example_474',
 'Example_476',
 'Example_477',
 'Example_473',
 'Example_478',
 'Example_472',
 'Example_475',
 'Example_1652',
 'Example_1647',
 'Example_1650',
 'Example_1651',
 'Example_1649',
 'Example_1648',
 'Example_1786',
 'Example_1787',
 'Example_1789',
 'Example_1784',
 'Example_1785',
 'Example_1790',
 'Example_1788',
 'Example_4656',
 'Example_4661',
 'Example_4662',
 'Example_4665',
 'Example_4657',
 'Example_4664',
 'Example_4659',
 'Example_4658',
 'Example_4660',
 'Example_4663',
 'Example_3807',
 'Example_3811',
 'Example_3809',
 'Example_3808',
 'Example_3810',
 'Example_3812',
 'Example_5353',
 'Example_5349',
 'Example_5350',
 'Example_5352',
 'Example_5351',
 'Example_5347',
 'Example_5354',
 'Example_5356',
 'Example_5355',
 'Example_5348',
 'Example_1237',
 'Example_1242',
 'Example_1236',
 'Example_1238',
 'Example_1233',
 'Example_1235',
 'Example_1234',
 'Example_1240',
 'Example_1239',
 'Example_1241',
 'Example_1232',
 'Example_3488',
 'Example_3490',
 'Example_3494',
 'Example_3492',
 'Example_3489',
 'Example_3493',
 'Example_3491',
 'Example_154',
 'Example_153',
 'Example_156',
 'Example_155',
 'Example_151',
 'Example_146',
 'Example_150',
 'Example_149',
 'Example_152',
 'Example_157',
 'Example_148',
 'Example_147',
 'Example_810',
 'Example_811',
 'Example_805',
 'Example_802',
 'Example_812',
 'Example_807',
 'Example_804',
 'Example_809',
 'Example_808',
 'Example_806',
 'Example_803',
 'Example_1465',
 'Example_1466',
 'Example_1470',
 'Example_1464',
 'Example_1468',
 'Example_1467',
 'Example_1469',
 'Example_2847',
 'Example_2850',
 'Example_2852',
 'Example_2848',
 'Example_2849',
 'Example_2851',
 'Example_4929',
 'Example_4924',
 'Example_4927',
 'Example_4928',
 'Example_4930',
 'Example_4925',
 'Example_4926',
 'Example_4923',
 'Example_2821',
 'Example_2822',
 'Example_2818',
 'Example_2819',
 'Example_2820',
 'Example_2823',
 'Example_523',
 'Example_524',
 'Example_521',
 'Example_518',
 'Example_519',
 'Example_522',
 'Example_525',
 'Example_520',
 'Example_526',
 'Example_2101',
 'Example_2098',
 'Example_2097',
 'Example_2099',
 'Example_2096',
 'Example_2100',
 'Example_555',
 'Example_556',
 'Example_553',
 'Example_552',
 'Example_557',
 'Example_554',
 'Example_551',
 'Example_1114',
 'Example_1113',
 'Example_1115',
 'Example_1110',
 'Example_1111',
 ...]

In [23]:
primary_df = df[df['name'].isin(all_examples)]
primary_df

,name,hasSentence,Example.Construction
3,Example_4724,"['892 in 2009.', 'Their average income fell to...",Subject(T) Verb(S)
19,Example_549,['Readers commenting on the story smelled a rat'],Verb(S) Direct Object(T)
30,Example_1824,['Virtual Radio Row: Christian McCaffrey expla...,Verb(S) Direct Object(T)
33,Example_2821,['$10-million gift has\xa0spirits soaring\xa0a...,Subject(T) Verb(S)
40,Example_4099,['I felt stabs of guilt for not visiting more ...,Noun(S) of Noun(T)
...,...,...,...
5567,Example_4097,['Suppose I contemplate something I did wrong ...,Noun(S) of Noun(T)
5591,Example_5129,"[""It's Christmastime. So"", 'give love on Chris...",Verb(S) Direct Object(T)
5593,Example_243,['people do come and assist with a warm smile ...,Adjective(S) Noun(T)
5595,Example_2681,['The group contains 60-ish members'],Subject(T) Verb(S)
5599,Example_142,['Why that open question has thrown Ontario la...,Verb(S) Direct Object(T)

In [24]:
primary_df['Example.Construction'].value_counts()

Example.Construction
Verb(S) Direct Object(T)              180
Subject(T) Verb(S)                    101
Adjective(S) Noun(T)                   91
Verb(S) preposition Noun(T)            83
Noun(S) of Noun(T)                     51
Adjective(T) Noun(S)                   27
Noun(S) preposition Noun(T)            22
Noun(T) copula Adjective(S)            20
Noun(T) copula Noun(S)                  7
Noun(T) copula preposition Noun(S)      7
Noun(T) Noun(S) Compound                3
Passive-Verb(S) by Noun(T)              2
Noun's(T) Noun(S)                       1
Name: count, dtype: int64

In [25]:
primary_df.name[primary_df["Example.Construction"] == "Verb(S) Direct Object(T)"].tolist()

['Example_549',
 'Example_1824',
 'Example_3490',
 'Example_3390',
 'Example_4711',
 'Example_436',
 'Example_1827',
 'Example_937',
 'Example_4650',
 'Example_2006',
 'Example_948',
 'Example_482',
 'Example_3492',
 'Example_3389',
 'Example_5309',
 'Example_5469',
 'Example_4707',
 'Example_518',
 'Example_4123',
 'Example_108',
 'Example_2128',
 'Example_3247',
 'Example_5126',
 'Example_2873',
 'Example_163',
 'Example_946',
 'Example_4139',
 'Example_557',
 'Example_138',
 'Example_941',
 'Example_1785',
 'Example_3489',
 'Example_654',
 'Example_5466',
 'Example_523',
 'Example_475',
 'Example_1826',
 'Example_1786',
 'Example_5125',
 'Example_525',
 'Example_552',
 'Example_3493',
 'Example_2874',
 'Example_485',
 'Example_3246',
 'Example_553',
 'Example_4141',
 'Example_555',
 'Example_520',
 'Example_4157',
 'Example_3488',
 'Example_472',
 'Example_2836',
 'Example_1922',
 'Example_2126',
 'Example_5304',
 'Example_657',
 'Example_1929',
 'Example_481',
 'Example_4487',
 'Example_4489',
 'Example_4827',
 'Example_728',
 'Example_1924',
 'Example_4121',
 'Example_656',
 'Example_942',
 'Example_1822',
 'Example_2187',
 'Example_3750',
 'Example_4229',
 'Example_5326',
 'Example_4710',
 'Example_140',
 'Example_5306',
 'Example_521',
 'Example_1823',
 'Example_3243',
 'Example_5303',
 'Example_945',
 'Example_114',
 'Example_4143',
 'Example_556',
 'Example_4158',
 'Example_4125',
 'Example_807',
 'Example_943',
 'Example_526',
 'Example_655',
 'Example_1068',
 'Example_1072',
 'Example_3394',
 'Example_5311',
 'Example_486',
 'Example_4122',
 'Example_944',
 'Example_949',
 'Example_2872',
 'Example_2002',
 'Example_2832',
 'Example_947',
 'Example_1928',
 'Example_4140',
 'Example_1070',
 'Example_3392',
 'Example_938',
 'Example_5449',
 'Example_1085',
 'Example_551',
 'Example_5305',
 'Example_5464',
 'Example_111',
 'Example_5127',
 'Example_474',
 'Example_5329',
 'Example_4828',
 'Example_2847',
 'Example_1923',
 'Example_484',
 'Example_4712',
 'Example_4940',
 'Example_731',
 'Example_136',
 'Example_440',
 'Example_1073',
 'Example_3494',
 'Example_2041',
 'Example_4492',
 'Example_1117',
 'Example_5307',
 'Example_5334',
 'Example_5016',
 'Example_162',
 'Example_2186',
 'Example_4120',
 'Example_1086',
 'Example_1825',
 'Example_139',
 'Example_2130',
 'Example_478',
 'Example_3245',
 'Example_1089',
 'Example_476',
 'Example_519',
 'Example_135',
 'Example_158',
 'Example_818',
 'Example_5314',
 'Example_2127',
 'Example_2005',
 'Example_2131',
 'Example_4156',
 'Example_5338',
 'Example_4124',
 'Example_3491',
 'Example_726',
 'Example_5450',
 'Example_2818',
 'Example_5455',
 'Example_554',
 'Example_3242',
 'Example_5310',
 'Example_524',
 'Example_5451',
 'Example_477',
 'Example_565',
 'Example_5467',
 'Example_5470',
 'Example_473',
 'Example_522',
 'Example_569',
 'Example_2902',
 'Example_5401',
 'Example_5325',
 'Example_5312',
 'Example_2900',
 'Example_110',
 'Example_4800',
 'Example_5129',
 'Example_142']

In [26]:
primary_df

,name,hasSentence,Example.Construction
3,Example_4724,"['892 in 2009.', 'Their average income fell to...",Subject(T) Verb(S)
19,Example_549,['Readers commenting on the story smelled a rat'],Verb(S) Direct Object(T)
30,Example_1824,['Virtual Radio Row: Christian McCaffrey expla...,Verb(S) Direct Object(T)
33,Example_2821,['$10-million gift has\xa0spirits soaring\xa0a...,Subject(T) Verb(S)
40,Example_4099,['I felt stabs of guilt for not visiting more ...,Noun(S) of Noun(T)
...,...,...,...
5567,Example_4097,['Suppose I contemplate something I did wrong ...,Noun(S) of Noun(T)
5591,Example_5129,"[""It's Christmastime. So"", 'give love on Chris...",Verb(S) Direct Object(T)
5593,Example_243,['people do come and assist with a warm smile ...,Adjective(S) Noun(T)
5595,Example_2681,['The group contains 60-ish members'],Subject(T) Verb(S)
5599,Example_142,['Why that open question has thrown Ontario la...,Verb(S) Direct Object(T)

In [27]:
primary_df[primary_df["Example.Construction"] == "Verb(S) Noun(T)"]

Empty DataFrame
Columns: [name, hasSentence, Example.Construction]
Index: []