In [1]:
import pandas as pd
import re
import ftfy
import spacy
from spacy import displacy
from tqdm import tqdm
import json

In [2]:
file_names = [
    'adjective_s_noun_t', 'adjective_t_noun_s', 'noun_s_of_noun_t', 'noun_s_prep_noun_t', 'noun_t_copula_adjective_s','noun_t_copula_noun_s', 'noun_t_copula_prep_noun_s', 'noun_t_noun_s', 'noun_t_verb_s', 'verb_s_prep_noun_t'
]

nlp = spacy.load("en_core_web_lg")

C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
def clean_text(s):
    if pd.isna(s):
        return ""
    s = ftfy.fix_text(str(s))                # fix unicode mojibake
    s = s.replace("\xa0"," ")                # non-breaking spaces
    s = re.sub(r"[\r\t]+", " ", s)           # remove stray control chars
    s = re.sub(r"\s+", " ", s).strip()       # collapse whitespace
    return s

# df['clean_text'] = df['text'].apply(clean_text)

In [7]:
import hashlib

def hashkey(x):
    return hashlib.md5(x.encode("utf-8")).hexdigest()

def process_main_data(f_name):
    df = pd.read_csv(f"data/raw/main/{f_name}.csv")
    df = df.rename(columns={"data": "text"})
    df['clean_text'] = df['text'].apply(clean_text)
    df['sentence_key'] = df['text'].apply(hashkey)
    df.to_csv(f'data/processed/main/{f_name}.csv')

for file in file_names:
    process_main_data(file)
# process_main_data('adjective_s_noun_t')
# process_main_data('adjective_t_noun_s')
# process_main_data('noun_s_of_noun_t')
# process_main_data('noun_s_prep_noun_t')
# process_main_data('noun_t_copula_adjective_s')
# process_main_data('noun_t_copula_noun_s')
# process_main_data('noun_t_copula_prep_noun_s')
# process_main_data('noun_t_noun_s')
# process_main_data('noun_t_verb_s')
# process_main_data('verb_s_prep_noun_t')

In [10]:
def make_articles(f_name):
    df = pd.read_csv(f"data/processed/main/{f_name}.csv")
    nlp = spacy.load("en_core_web_lg")
    texts = df['clean_text'].copy()
    docs = []
    for text in texts:
        doc = nlp(text)
        docs.append(doc)

    texts_df = pd.DataFrame(texts)
    texts_df.columns = ["articles"]
    articles_json = {
        "articles": texts_df["articles"].tolist()
    }
    with open(f"data/processed/main/articles/{f_name}_articles.json", "w", encoding="utf-8") as f:
        json.dump(articles_json, f, ensure_ascii=False, indent=2)

    keys_json = {
        "sentence_keys": df["sentence_key"].tolist()
    }

    with open(f"data/processed/main/articles/{f_name}_article_keys.json", "w", encoding="utf-8") as f:
        json.dump(keys_json, f, ensure_ascii=False, indent=2)

for file in file_names:
    make_articles(file)

C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
C:\Users\micah\PycharmProjects\computational_linguistics\.venv\Lib\site-packages\spacy\util.py:894: UserWarning: [W095] Model 'en_core_web_lg' (3.8.0) was trained with spaCy v3.8.0 and may not be 100% compatible with the current version (4.0.0.dev3). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

From here, I used inference.py in the models folder to generate the tsv with the predictions. It was written as a terminal script so I revised it there vs adjusting it to make it work in the notebook.

In [10]:
def load_tsv(f_name):
    df = pd.read_csv(f"data/processed/main/articles/predictions/{f_name}_predictions.tsv", sep="\t")
    return df

In [11]:
tsv_list = []

for file in file_names:
    tsv_list.append(load_tsv(file))

tsv_list

[       Article  Sentence       Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0  too-forward                    0               0
 1            0         0            .                    0               0
 2            0         1        Maybe                    0               0
 3            0         1          the                    0               0
 4            0         1         only                    0               0
 ...        ...       ...          ...                  ...             ...
 55507     1793         1     reaching                    1               1
 55508     1793         1           to                    0               0
 55509     1793         1           be                    0               0
 55510     1793         1       picked                    0               0
 55511     1793         1           up                    0               0

          Frame_label
 0                  _
 1                  _
 2         Likelihood
 3                  _
 4      Sole_instance
 ...              ...
 55507    Self_motion
 55508              _
 55509              _
 55510   Cause_motion
 55511              _

 [55512 rows x 6 columns],
        Article  Sentence     Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0         As                    0               0
 1            0         0      Brian                    0               0
 2            0         0  Baldinger                    0               0
 3            0         0         of                    0               0
 4            0         0    NFL.com                    0               0
 ...        ...       ...        ...                  ...             ...
 47106     1519         1       will                    0               0
 47107     1519         1       deny                    0               0
 47108     1519         1       thee                    0               0
 47109     1519         1    nothing                    0               0
 47110     1519         1          :                    0               0

           Frame_label
 0                   _
 1                   _
 2                   _
 3                   _
 4                   _
 ...               ...
 47106               _
 47107  Affirm_or_deny
 47108               _
 47109               _
 47110               _

 [47111 rows x 6 columns],
       Article  Sentence   Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0        #                    0               0
 1           0         0     upon                    1               0
 2           0         0      you                    0               0
 3           0         0        ;                    0               0
 4           0         0       it                    0               0
 ...       ...       ...      ...                  ...             ...
 7371      284         1     wins                    1               0
 7372      284         1        .                    0               0
 7373      284         2        #                    0               0
 7374      284         2        I                    0               0
 7375      284         2  suspect                    0               0

              Frame_label
 0                      _
 1        Spatial_contact
 2                      _
 3                      _
 4                      _
 ...                  ...
 7371  Finish_competition
 7372                   _
 7373                   _
 7374                   _
 7375           Awareness

 [7376 rows x 6 columns],
        Article  Sentence  Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0     the                    0               0
 1            0         0    past                    0               0
 2            0         0       .                    0               0
 3            0         1  Credit                    0               0
 4            0         1       :                    0               0
 ...        ...       ...     ...                  ...             ...
 64250     2078         1    when                    0               0
 64251     2078         1       a                    0               0
 64252     2078         1   child                    0               0
 64253     2078         1   cries                    0               0
 64254     2078         1       ,                    0               0

                 Frame_label
 0                         _
 1        Individual_history
 2                         _
 3                         _
 4                         _
 ...                     ...
 64250  Temporal_collocation
 64251                     _
 64252         People_by_age
 64253   Communication_noise
 64254                     _

 [64255 rows x 6 columns],
       Article  Sentence    Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0   between                    1               0
 1           0         0       the                    0               0
 2           0         0       two                    0               0
 3           0         0         :                    0               0
 4           0         0   Nuclear                    0               0
 ...       ...       ...       ...                  ...             ...
 2922       93         3        of                    0               0
 2923       93         3  pressure                    1               1
 2924       93         3   without                    1               0
 2925       93         3    making                    1               0
 2926       93         3       her                    0               0

            Frame_label
 0                    _
 1                    _
 2     Cardinal_numbers
 3                    _
 4                    _
 ...                ...
 2922                 _
 2923                 _
 2924                 _
 2925      Cause_change
 2926                 _

 [2927 rows x 6 columns],
       Article  Sentence      Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0      before                    1               0
 1           0         0         the                    0               0
 2           0         0  locomotive                    0               0
 3           0         0         age                    0               0
 4           0         0          ``                    0               0
 ...       ...       ...         ...                  ...             ...
 1139       36         2           )                    0               0
 1140       36         2      Denzel                    0               0
 1141       36         2  Washington                    0               0
 1142       36         2     directs                    0               0
 1143       36         2         and                    0               0

          Frame_label
 0        Time_vector
 1                  _
 2            Vehicle
 3     Calendric_unit
 4                  _
 ...              ...
 1139               _
 1140               _
 1141               _
 1142               _
 1143               _

 [1144 rows x 6 columns],
      Article  Sentence       Tokens  Borderline_metaphor  Real_metaphors  \
 0          0         0       system                    1               0
 1          0         0       should                    0               0
 2          0         0          n't                    0               0
 3          0         0       depend                    0               0
 4          0         0           on                    1               0
 ..       ...       ...          ...                  ...             ...
 487       15         1           is                    0               0
 488       15         1    portrayed                    0               0
 489       15         1           in                    1               0
 490       15         1          her                    0               0
 491       15         1  performance                    0               0

                     Frame_label
 0                        System
 1               Desirable_event
 2                             _
 3                   Contingency
 4                             _
 ..                          ...
 487                           _
 488  Communicate_categorization
 489                           _
 490                           _
 491        Performers_and_roles

 [492 rows x 6 columns],
        Article  Sentence      Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0       sorry                    0               0
 1            0         0          to                    0               0
 2            0         0  disappoint                    0               0
 3            0         0         you                    0               0
 4            0         0           .                    0               0
 ...        ...       ...         ...                  ...             ...
 32111     1039         1          ``                    0               0
 32112     1039         1         the                    0               0
 32113     1039         1    American                    0               0
 32114     1039         1  Ambassador                    0               0
 32115     1039         1          ``                    0               0

              Frame_label
 0      Experiencer_focus
 1                      _
 2        Experiencer_obj
 3                      _
 4                      _
 ...                  ...
 32111                  _
 32112                  _
 32113             Origin
 32114         Leadership
 32115                  _

 [32116 rows x 6 columns],
        Article  Sentence        Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0          Some                    0               0
 1            0         0      children                    0               0
 2            0         0         enter                    1               0
 3            0         0  kindergarten                    0               0
 4            0         0          with                    1               0
 ...        ...       ...           ...                  ...             ...
 94537     3050         1          lamb                    0               0
 94538     3050         1            's                    0               0
 94539     3050         1          soft                    0               0
 94540     3050         1        fleece                    0               0
 94541     3050         1             .                    0               0

                  Frame_label
 0      Proportional_quantity
 1                    Kinship
 2             Activity_start
 3                          _
 4                          _
 ...                      ...
 94537                      _
 94538                      _
 94539  Measurable_attributes
 94540                      _
 94541                      _

 [94542 rows x 6 columns],
        Article  Sentence  Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0       ,                    0               0
 1            0         0   which                    0               0
 2            0         0      we                    0               0
 3            0         0     can                    0               0
 4            0         0     not                    0               0
 ...        ...       ...     ...                  ...             ...
 27717      895         0    with                    1               0
 27718      895         0     the                    0               0
 27719      895         0   facts                    0               0
 27720      895         0      of                    0               0
 27721      895         0  Carter                    0               0

       Frame_label
 0               _
 1               _
 2               _
 3      Capability
 4               _
 ...           ...
 27717           _
 27718           _
 27719           _
 27720           _
 27721           _

 [27722 rows x 6 columns]]

In [ ]:
def load_tsv_v2(f_name):
    df = pd.read_csv(f"data/processed/main/articles/predictions/v2/{f_name}_predictions.tsv", sep="\t")
    return df

tsv_list_v2 = []

for file in file_names:
    tsv_list_v2.append(load_tsv(file))

tsv_list_v2

In [12]:
def safe_lemmatize(token):
    if isinstance(token, str):
        return nlp(token)[0].lemma_
    else:
        return token

In [14]:
### long long runtime so don't rerun unless you have to

for dataframe in tsv_list:
    dataframe["Token_lemma"] = dataframe["Tokens"].apply(safe_lemmatize)

tsv_list

[       Article  Sentence       Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0  too-forward                    0               0
 1            0         0            .                    0               0
 2            0         1        Maybe                    0               0
 3            0         1          the                    0               0
 4            0         1         only                    0               0
 ...        ...       ...          ...                  ...             ...
 55507     1793         1     reaching                    1               1
 55508     1793         1           to                    0               0
 55509     1793         1           be                    0               0
 55510     1793         1       picked                    0               0
 55511     1793         1           up                    0               0

          Frame_label Token_lemma
 0                  _         too
 1                  _           .
 2         Likelihood       maybe
 3                  _         the
 4      Sole_instance        only
 ...              ...         ...
 55507    Self_motion       reach
 55508              _          to
 55509              _          be
 55510   Cause_motion        pick
 55511              _          up

 [55512 rows x 7 columns],
        Article  Sentence     Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0         As                    0               0
 1            0         0      Brian                    0               0
 2            0         0  Baldinger                    0               0
 3            0         0         of                    0               0
 4            0         0    NFL.com                    0               0
 ...        ...       ...        ...                  ...             ...
 47106     1519         1       will                    0               0
 47107     1519         1       deny                    0               0
 47108     1519         1       thee                    0               0
 47109     1519         1    nothing                    0               0
 47110     1519         1          :                    0               0

           Frame_label Token_lemma
 0                   _          as
 1                   _       Brian
 2                   _   Baldinger
 3                   _          of
 4                   _     NFL.com
 ...               ...         ...
 47106               _        will
 47107  Affirm_or_deny        deny
 47108               _        thee
 47109               _     nothing
 47110               _           :

 [47111 rows x 7 columns],
       Article  Sentence   Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0        #                    0               0
 1           0         0     upon                    1               0
 2           0         0      you                    0               0
 3           0         0        ;                    0               0
 4           0         0       it                    0               0
 ...       ...       ...      ...                  ...             ...
 7371      284         1     wins                    1               0
 7372      284         1        .                    0               0
 7373      284         2        #                    0               0
 7374      284         2        I                    0               0
 7375      284         2  suspect                    0               0

              Frame_label Token_lemma
 0                      _           #
 1        Spatial_contact        upon
 2                      _         you
 3                      _           ;
 4                      _          it
 ...                  ...         ...
 7371  Finish_competition         win
 7372                   _           .
 7373                   _           #
 7374                   _           I
 7375           Awareness     suspect

 [7376 rows x 7 columns],
        Article  Sentence  Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0     the                    0               0
 1            0         0    past                    0               0
 2            0         0       .                    0               0
 3            0         1  Credit                    0               0
 4            0         1       :                    0               0
 ...        ...       ...     ...                  ...             ...
 64250     2078         1    when                    0               0
 64251     2078         1       a                    0               0
 64252     2078         1   child                    0               0
 64253     2078         1   cries                    0               0
 64254     2078         1       ,                    0               0

                 Frame_label Token_lemma
 0                         _         the
 1        Individual_history        past
 2                         _           .
 3                         _      credit
 4                         _           :
 ...                     ...         ...
 64250  Temporal_collocation        when
 64251                     _           a
 64252         People_by_age       child
 64253   Communication_noise         cry
 64254                     _           ,

 [64255 rows x 7 columns],
       Article  Sentence    Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0   between                    1               0
 1           0         0       the                    0               0
 2           0         0       two                    0               0
 3           0         0         :                    0               0
 4           0         0   Nuclear                    0               0
 ...       ...       ...       ...                  ...             ...
 2922       93         3        of                    0               0
 2923       93         3  pressure                    1               1
 2924       93         3   without                    1               0
 2925       93         3    making                    1               0
 2926       93         3       her                    0               0

            Frame_label Token_lemma
 0                    _     between
 1                    _         the
 2     Cardinal_numbers         two
 3                    _           :
 4                    _     nuclear
 ...                ...         ...
 2922                 _          of
 2923                 _    pressure
 2924                 _     without
 2925      Cause_change        make
 2926                 _         she

 [2927 rows x 7 columns],
       Article  Sentence      Tokens  Borderline_metaphor  Real_metaphors  \
 0           0         0      before                    1               0
 1           0         0         the                    0               0
 2           0         0  locomotive                    0               0
 3           0         0         age                    0               0
 4           0         0          ``                    0               0
 ...       ...       ...         ...                  ...             ...
 1139       36         2           )                    0               0
 1140       36         2      Denzel                    0               0
 1141       36         2  Washington                    0               0
 1142       36         2     directs                    0               0
 1143       36         2         and                    0               0

          Frame_label Token_lemma
 0        Time_vector      before
 1                  _         the
 2            Vehicle  locomotive
 3     Calendric_unit         age
 4                  _           `
 ...              ...         ...
 1139               _           )
 1140               _      Denzel
 1141               _  Washington
 1142               _      direct
 1143               _         and

 [1144 rows x 7 columns],
      Article  Sentence       Tokens  Borderline_metaphor  Real_metaphors  \
 0          0         0       system                    1               0
 1          0         0       should                    0               0
 2          0         0          n't                    0               0
 3          0         0       depend                    0               0
 4          0         0           on                    1               0
 ..       ...       ...          ...                  ...             ...
 487       15         1           is                    0               0
 488       15         1    portrayed                    0               0
 489       15         1           in                    1               0
 490       15         1          her                    0               0
 491       15         1  performance                    0               0

                     Frame_label  Token_lemma
 0                        System       system
 1               Desirable_event       should
 2                             _          not
 3                   Contingency       depend
 4                             _           on
 ..                          ...          ...
 487                           _           be
 488  Communicate_categorization      portray
 489                           _           in
 490                           _          she
 491        Performers_and_roles  performance

 [492 rows x 7 columns],
        Article  Sentence      Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0       sorry                    0               0
 1            0         0          to                    0               0
 2            0         0  disappoint                    0               0
 3            0         0         you                    0               0
 4            0         0           .                    0               0
 ...        ...       ...         ...                  ...             ...
 32111     1039         1          ``                    0               0
 32112     1039         1         the                    0               0
 32113     1039         1    American                    0               0
 32114     1039         1  Ambassador                    0               0
 32115     1039         1          ``                    0               0

              Frame_label Token_lemma
 0      Experiencer_focus       sorry
 1                      _          to
 2        Experiencer_obj  disappoint
 3                      _         you
 4                      _           .
 ...                  ...         ...
 32111                  _           `
 32112                  _         the
 32113             Origin    american
 32114         Leadership  Ambassador
 32115                  _           `

 [32116 rows x 7 columns],
        Article  Sentence        Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0          Some                    0               0
 1            0         0      children                    0               0
 2            0         0         enter                    1               0
 3            0         0  kindergarten                    0               0
 4            0         0          with                    1               0
 ...        ...       ...           ...                  ...             ...
 94537     3050         1          lamb                    0               0
 94538     3050         1            's                    0               0
 94539     3050         1          soft                    0               0
 94540     3050         1        fleece                    0               0
 94541     3050         1             .                    0               0

                  Frame_label   Token_lemma
 0      Proportional_quantity          some
 1                    Kinship         child
 2             Activity_start         enter
 3                          _  kindergarten
 4                          _          with
 ...                      ...           ...
 94537                      _          lamb
 94538                      _            be
 94539  Measurable_attributes          soft
 94540                      _        fleece
 94541                      _             .

 [94542 rows x 7 columns],
        Article  Sentence  Tokens  Borderline_metaphor  Real_metaphors  \
 0            0         0       ,                    0               0
 1            0         0   which                    0               0
 2            0         0      we                    0               0
 3            0         0     can                    0               0
 4            0         0     not                    0               0
 ...        ...       ...     ...                  ...             ...
 27717      895         0    with                    1               0
 27718      895         0     the                    0               0
 27719      895         0   facts                    0               0
 27720      895         0      of                    0               0
 27721      895         0  Carter                    0               0

       Frame_label Token_lemma
 0               _           ,
 1               _       which
 2               _          we
 3      Capability         can
 4               _         not
 ...           ...         ...
 27717           _        with
 27718           _         the
 27719           _        fact
 27720           _          of
 27721           _      Carter

 [27722 rows x 7 columns]]

In [15]:
# temporary files to avoid rerunning lemmatizing
for name, df in zip(file_names, tsv_list):
    df.to_csv(f"data/processed/main/articles/predictions/tmp/{name}_predictions.csv", index=False)

In [25]:
# doing this to see how effectively it can id the target lemmas in the data

lemma_list = []

with open("../workflow/data/word_lists_primary_only.txt", "r") as f:
    text = f.read()

text_blocks = text.strip().split("\n\n")
for block in text_blocks:
    lines = block.split("\n")
    lemma_list.extend(lines[1:])

lemma_list = list(set(lemma_list))
lemma_list

['salivate',
 'happiness',
 'slosh',
 'yearn',
 'object',
 'gladness',
 'blindness',
 'watery',
 'movement',
 'hiss',
 'accumulation',
 'difficulty',
 'gleefulness',
 'think',
 'opportunities',
 'many',
 'believe',
 'drift',
 'thought',
 'solidity',
 'another',
 'goose-step',
 'roadway',
 'underpin',
 'functionality',
 'lane',
 'slop',
 'pump',
 'catch',
 'vanquishment',
 'mad',
 'food',
 'chance',
 'peckish',
 'hot',
 'battle',
 'outraged',
 'awful',
 'bow',
 'adversity',
 'badness',
 'well-lit',
 'hankering',
 'immobile',
 'winding',
 'seize',
 'spring',
 'large',
 'trickle',
 'route',
 'brighten',
 'causation',
 'toasty',
 'assess',
 'help',
 'warmth',
 'training',
 'unmoving',
 'see',
 'channel',
 'sensation',
 'troop',
 'street',
 'tranquility',
 'set',
 'overjoyed',
 'get',
 'length',
 'supporting',
 'kiss',
 'prosperous',
 'actor',
 'several',
 'waterfall',
 'behind',
 'easygoing',
 'harm',
 'add',
 'joust',
 'hungry',
 'link',
 'thinking',
 'spar',
 'increase',
 'modification',
 'superhighway',
 'irate',
 'size',
 'wake-up',
 'damage',
 'location',
 'worse',
 'serene',
 'wake',
 'agonizing',
 'move',
 'tide',
 'luminous',
 'squirt',
 'crookedness',
 'meat',
 'something',
 'assessment',
 'melee',
 'cavort',
 'tantrum',
 'splash',
 'crooked',
 'shower',
 'untainted',
 'inundate',
 'yen',
 'brilliant',
 'lunge',
 'covetousness',
 'engorge',
 'intuition',
 'huge',
 'power',
 'skirmish',
 'setting',
 'motion',
 'arced',
 'placidity',
 'tactile',
 'debate',
 'is',
 'contemplate',
 'weight',
 'gush',
 'dwell',
 'teeny',
 'container',
 'inch',
 'within',
 'wellness',
 'cleanliness',
 'fluid',
 'related',
 'water',
 'impede',
 'stream',
 'rich',
 'still',
 'bitty',
 'able-bodied',
 'locale',
 'less',
 'controlled',
 'introspection',
 'hurtle',
 'build',
 'battlefield',
 'blinder',
 'accumulate',
 'boundary',
 'anything',
 'clinch',
 'central',
 'region',
 'cuddle',
 'struggle',
 'appraise',
 'thing',
 'appraisal',
 'temporal',
 'humid',
 'river',
 'few',
 'fervency',
 'ravenous',
 'be',
 'snuggle',
 'rage',
 'peacefulness',
 'assumption',
 'receive',
 'ardent',
 'act',
 'grapple',
 'runoff',
 'painfully',
 'bridge',
 'structure',
 'combatant',
 'run',
 'achy',
 'control',
 'dribble',
 'resource',
 'alley',
 'difficulties',
 'rouse',
 'ooze',
 'step',
 'well-being',
 'assistance',
 'inform',
 'pollution',
 'elation',
 'drool',
 'immovable',
 'victory',
 'do',
 'understanding',
 'asset',
 'aching',
 'lighten',
 'straight',
 'horribleness',
 'communicate',
 'forcible',
 'flood',
 'moral',
 'soldier',
 'construct',
 'enormous',
 'gap',
 'speculation',
 'drain',
 'bent',
 'width',
 'idea',
 'ravenousness',
 'warm',
 'back',
 'spew',
 'hunch',
 'group',
 'time',
 'difficult',
 'revolution',
 'chain',
 'soothing',
 'business',
 'stride',
 'revise',
 'soothe',
 'take',
 'force',
 'understand',
 'forecast',
 'shape',
 'duke',
 'drench',
 'joy',
 'big',
 'infuriated',
 'glaring',
 'entity',
 'motionless',
 'fight',
 'glare',
 'snatch',
 'unfazed',
 'serenity',
 'perceiver',
 'tell',
 'wave',
 'blindfold',
 'cascade',
 'awake',
 'relax',
 'stability',
 'hurt',
 'clamber',
 'obtain',
 'conquer',
 'outside',
 'containable',
 'apart',
 'firmness',
 'spotless',
 'capital',
 'malodorous',
 'fountain',
 'brace',
 'toastiness',
 'overwhlem',
 'allies',
 'revision',
 'core',
 'unanxious',
 'prosperity',
 'wealth',
 'passage',
 'worst',
 'wealthy',
 'rainy',
 'feeling',
 'byway',
 'combat',
 'box',
 'laid-back',
 'speculate',
 'snowy',
 'appetite',
 'pressure',
 'addition',
 'strap',
 'company',
 'crawl',
 'centre',
 'much',
 'avenue',
 'center',
 'rigidity',
 'rice',
 'action',
 'glee',
 'augmentation',
 'brim',
 'industry',
 'point',
 'bound',
 'pathway',
 'drainage',
 'undiluted',
 'jog',
 'lollop',
 'affluence',
 'unadulterated',
 'area',
 'decrease',
 'blitzkrieg',
 'snow',
 'liquid',
 'stationary',
 'craving',
 'snack',
 'pollute',
 'reeking',
 'well-heeled',
 'pained',
 'comprehend',
 'totter',
 'vanquish',
 'foodstuff',
 'alliance',
 'shoulder',
 'nourishment',
 'skim',
 'miniature',
 'happy',
 'support',
 'supportive',
 'agony',
 'bright',
 'way',
 'straightness',
 'fervor',
 'sight',
 'expansive',
 'besiege',
 'saunter',
 'destabilize',
 'tread',
 'gleeful',
 'crave',
 'functional',
 'foul-smelling',
 'color',
 'overflow',
 'ripple',
 'belief',
 'pristine',
 'reinforce',
 'joyfulness',
 'hanker',
 'acquire',
 'unbothered',
 'learning',
 'ally',
 'placidness',
 'clomp',
 'awaken',
 'perceive',
 'stagger',
 'shift',
 'communication',
 'want',
 'promenade',
 'weather',
 'turnpike',
 'march',
 'deforestation',
 'desire',
 'highway',
 'healthful',
 'war',
 'spurt',
 'hop',
 'relaxing',
 'passionate',
 'path',
 'speed',
 'eddy',
 'itself',
 'glad',
 'regain',
 'pour',
 'drip',
 'amount',
 'backward',
 'bubble',
 'devour',
 'dazzling',
 'blinded',
 'bear-hug',
 'healthiness',
 'curvy',
 'supportable',
 'relaxed',
 'suffer',
 'awakened',
 'alert',
 'comprehension',
 'unworried',
 'quantity',
 'famine',
 'concept',
 'yearning',
 'peeved',
 'pure',
 'furious',
 'lightness',
 'twisting',
 'anger',
 'emotion',
 'thirsty',
 'vertical',
 'little',
 'embrace',
 'stinky',
 'dance',
 'richest',
 'aisle',
 'everything',
 'fishy',
 'climate',
 'crises',
 'vision',
 'connector',
 'richer',
 'aid',
 'gorge',
 'painful',
 'unperturbed',
 'purity',
 'notion',
 'transform',
 'inside',
 'stink',
 'pain',
 'covet',
 'clash',
 'minefield',
 'sunny',
 'motionlessness',
 'out',
 'voice',
 'healthy',
 'criticism',
 'harmful',
 'bomb',
 'uncontainable',
 'ire',
 'relaxation',
 'contained',
 'freeway',
 'skyway',
 'more',
 'cleansed',
 'row',
 'claim',
 'eating',
 'stock-still',
 'passion',
 'track',
 'road',
 'augment',
 'ardor',
 'sweep',
 'brawl',
 'soak',
 'miniscule',
 'seep',
 'trail',
 'longing',
 'mobile',
 'blinders',
 'effect',
 'stinking',
 'controllable',
 'untroubled',
 'hardness',
 'nibble',
 'smelly',
 'it',
 'fasttrack',
 'terribleness',
 'health',
 'gobble',
 'purl',
 'morality',
 'placid',
 'massive',
 'bombard',
 'calmness',
 'bread',
 'honey',
 'existence',
 'hassle',
 'eat',
 'warrior',
 'well-to-do',
 'show',
 'parkway',
 'joyful',
 'munchies',
 'study',
 'ebb',
 'foe',
 'strife',
 'wakeful',
 'battleground',
 'erudition',
 'assist',
 'crisis',
 'perception',
 'lifecycle',
 'sphere',
 'surge',
 'tiny',
 'warmness',
 'site',
 'wakefulness',
 'thoroughfare',
 'powerful',
 'introspect',
 'bond',
 'arouse',
 'go',
 'fury',
 'helper',
 'education',
 'leak',
 'twinge',
 'contain',
 'relationship',
 'pang',
 'possession',
 'suspicion',
 'reserve',
 'linger',
 'binding',
 'helpful',
 'twisty',
 'forceful',
 'connection',
 'educational',
 'locate',
 'scuffle',
 'heat',
 'reek',
 'sprint',
 'cause',
 'vault',
 'arise',
 'warfare',
 'peaceful',
 'thirst',
 'conceptualization',
 'most',
 'overheat',
 'sugar',
 'goosestep',
 'complication',
 'weathliest',
 'spout',
 'curved',
 'duel',
 'awoke',
 'carefree',
 'wrestle',
 'evaluation',
 'periphery',
 'stillness',
 'combative',
 'creep',
 'lurch',
 'impassioned',
 'assume',
 'place',
 'stable',
 'distress',
 'passionateness',
 'nourish',
 'expressway',
 'tranquil',
 'in',
 'ache',
 'bind',
 'clean',
 'tie',
 'seige',
 'learn',
 'touch',
 'argument',
 'rearward',
 'windy',
 'blind',
 'emotional',
 'uncontrollable',
 'containment',
 'mobility',
 'unstirring',
 'hug',
 'caress',
 'angry',
 'sensory',
 'excruciating',
 'slide',
 'brilliance',
 'uncontrolled',
 'spray',
 'sense',
 'ecstatic',
 'wrangle',
 'lighted',
 'awfulness',
 'calm',
 'evaluate',
 'feed',
 'ownership',
 'feel',
 'brightness',
 'pedagogy',
 'bop',
 'caper',
 'bad',
 'backwards',
 'blitz',
 'transformation',
 'well-off',
 'small',
 'stabilize',
 'speak',
 'candy',
 'torpedo',
 'connect',
 'change',
 'relate',
 'geyser',
 'smog',
 'flow',
 'exist',
 'musing',
 'hunger',
 'hardship',
 'mass',
 'possess',
 'acquisition',
 'beltway',
 'suffering',
 'outrage',
 'own',
 'address',
 'contemplation',
 'conquest',
 'enemy',
 'boulevard',
 'transfer',
 'owner',
 'elated',
 'neighborhood',
 'temperature',
 'illuminated',
 'walk',
 'stench',
 'gain',
 'verticality',
 'hobble',
 'riches',
 'awash',
 'terrible',
 'splatter',
 'ambush',
 'meal',
 'spill',
 'gigantic',
 'modify',
 'warmish',
 'some',
 'pace',
 'tussle',
 'peripheral',
 'hotness',
 'outpouring',
 'rain',
 'horrible',
 'opportunity']

In [63]:
# tsv_list[0]['is_target'] = tsv_list[0].Token_lemma.isin(lemma_list)
# tsv_list[0]['pair_flag'] = tsv_list[0].is_target & tsv_list[0].is_target.shift(-1)
tsv_list[0][tsv_list[0].Article == 1331]

,Article,Sentence,Tokens,Borderline_metaphor,Real_metaphors,Frame_label,Token_lemma,is_target,pair_flag
41209,1331,0,54486,0,0,_,54486,False,False
41210,1331,0,LIQUID,0,0,_,liquid,True,True
41211,1331,0,ASSETS,0,0,_,asset,True,False
41212,1331,0,CHARLES-OSGOOD-ho,0,0,_,CHARLES,False,False
41213,1331,0,:,0,0,_,:,False,False
41214,1331,0,To,0,0,_,to,False,False
41215,1331,0,turn,1,0,Cause_change,turn,False,False
41216,1331,0,used,0,0,Using,use,False,False
41217,1331,0,tin,0,0,Substance,tin,False,False
41218,1331,0,cans,0,0,Containers,can,False,False
41219,1331,0,into,0,0,_,into,False,False
41220,1331,0,Liquid,1,1,_,liquid,True,True
41221,1331,0,Assets,0,0,Possession,asset,True,False
41222,1331,0,and,0,0,_,and,False,False
41223,1331,0,dreams,1,1,_,dream,False,False
41224,1331,0,into,1,0,_,into,False,False
41225,1331,0,reality,0,0,_,reality,False,False
41226,1331,0,is,0,0,_,be,True,False
41227,1331,0,n't,0,0,_,not,False,False
41228,1331,0,easy,0,0,Difficulty,easy,False,False
41229,1331,0,.,0,0,_,.,False,False
41230,1331,1,But,0,0,_,but,False,False
41231,1331,1,it,0,0,_,it,True,False
41232,1331,1,can,0,0,Capability,can,False,False
41233,1331,1,be,0,0,_,be,True,True
41234,1331,1,done,0,0,Intentionally_act,do,True,False
41235,1331,1,and,0,0,_,and,False,False

In [64]:
orig_df = []

for file in file_names:
    orig_df.append(pd.read_csv(f"data/processed/main/{file}.csv"))

orig_df

[      Unnamed: 0   lemma_1  lemma_2  year genre                     source  \
 0              0  backward     time  2019   FIC                     Analog
 1              1  backward     time  2019  ACAD           Tehnicki Vjesnik
 2              2  backward     time  2017   MAG                    Nerdist
 3              3  backward     time  2012  ACAD               PhysicsToday
 4              4  backward     time  2012  ACAD               PhysicsToday
 ...          ...       ...      ...   ...   ...                        ...
 1789        1789      warm   caress  2009  NEWS                    Houston
 1790        1790      warm   caress  1996  SPOK               PBS_Newshour
 1791        1791      warm   caress  1995   FIC               FantasySciFi
 1792        1792      warm   caress  1994   MOV  That's Entertainment! III
 1793        1793      warm  snuggle  2012  BLOG    ...rstress.blogspot.com

                                                    text  \
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

                                              clean_text
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

 [1794 rows x 8 columns],
       Unnamed: 0    lemma_1  lemma_2  year genre                   source  \
 0              0  difficult    catch  2019   MAG          Bleacher Report
 1              1  difficult    catch  2019  NEWS            Baltimore Sun
 2              2  difficult    catch  2018  NEWS        Chicago Sun-Times
 3              3  difficult    catch  2017  NEWS        Los Angeles Times
 4              4  difficult    catch  2012  BLOG       nflgridirongab.com
 ...          ...        ...      ...   ...   ...                      ...
 1515        1515    helpful  support  1992   MAG                Astronomy
 1516        1516      blind    touch  2008   FIC                   Poetry
 1517        1517      blind    touch  2000  SPOK                CNN_Event
 1518        1518      blind  feeling  2003  ACAD              PerspPolSci
 1519        1519  difficult   weight  2012   WEB  ...peare-literature.com

                                                    text  \
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

                                              clean_text
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

 [1520 rows x 8 columns],
      Unnamed: 0      lemma_1    lemma_2  year genre                   source  \
 0             0         back       time  2015   FIC             Ploughshares
 1             1         back       time  2012   WEB               amazon.com
 2             2         back       time  1990   FIC             VirginiaQRev
 3             3         area  existence  2012  BLOG  ...documentaryfilms.com
 4             4         area  existence  1996   FIC                   Tikkun
 ..          ...          ...        ...   ...   ...                      ...
 280         280       battle      point  1994  SPOK                  NPR_ATC
 281         281  battlefield     debate  2012  BLOG             theblaze.com
 282         282        blitz  criticism  2012   WEB                slate.com
 283         283   blitzkrieg  criticism  2009  SPOK                 CNN_Misc
 284         284          war   argument  2012  BLOG  ...rongwiththeworld.net

                                                   text  \
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

                                             clean_text
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

 [285 rows x 8 columns],
       Unnamed: 0     lemma_1    lemma_2  year genre                 source  \
 0              0        back       time  2018   MAG               Phys.Org
 1              1        back       time  2018   MAG       News-Medical.net
 2              2        back       time  2018   MAG   News-Medical.net (4)
 3              3        back       time  2017  NEWS  Chicago Sun-Times (3)
 4              4        back       time  2017    TV        Hap and Leonard
 ...          ...         ...        ...   ...   ...                    ...
 2074        2074       blitz  criticism  2012   WEB              slate.com
 2075        2075  blitzkrieg  criticism  2009  SPOK               CNN_Misc
 2076        2076       enemy     debate  2010   MAG             USCatholic
 2077        2077       troop      point  2012   WEB           shtfplan.com
 2078        2078      warmth        hug  2002   MAG              Parenting

                                                    text  \
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

                                              clean_text
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

 [2079 rows x 8 columns],
     Unnamed: 0   lemma_1    lemma_2  year genre                   source  \
 0            0     power  expansive  2004  ACAD              Environment
 1            1   feeling       hurt  2018   FIC             Ploughshares
 2            2   feeling       hurt  2012   WEB              squidoo.com
 3            3   feeling       hurt  2012  BLOG          firebrandal.com
 4            4   feeling       hurt  2012  BLOG  ...ekgirl.wordpress.com
 ..         ...       ...        ...   ...   ...                      ...
 89          89  quantity       tiny  2012  BLOG      investinmiskolc.com
 90          90   control   vertical  1993  SPOK              CBS_Morning
 91          91      kiss       warm  2006   FIC                  Redbook
 92          92      kiss       warm  2005   MAG             Cosmopolitan
 93          93      kiss       warm  1999   FIC             Cosmopolitan

                                                  text  \
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

                                            clean_text
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

 [94 rows x 8 columns],
     Unnamed: 0       lemma_1       lemma_2  year genre  \
 0            0          time      location  2004  ACAD
 1            1          time  neighborhood  2005  SPOK
 2            2          idea          food  2018  SPOK
 3            3          idea          food  2012   WEB
 4            4          idea         sugar  2012  BLOG
 5            5       thought          food  2019   FIC
 6            6         cause          food  2012  BLOG
 7            7         cause          food  2012  BLOG
 8            8         cause          food  2006   MAG
 9            9        desire        hunger  2012   WEB
 10          10        desire        hunger  2010  SPOK
 11          11      resource         water  1998  ACAD
 12          12      resource         water  1990   MAG
 13          13       feeling            go  2000  SPOK
 14          14          time            go  2017  SPOK
 15          15          time            go  2012   WEB
 16          16          time            go  2012  BLOG
 17          17          time            go  2011  SPOK
 18          18       emotion         thing  2016  ACAD
 19          19       emotion         thing  2014  ACAD
 20          20       emotion         thing  2012  SPOK
 21          21        chance         thing  2012  BLOG
 22          22        chance         thing  2002   FIC
 23          23        chance         thing  2001  NEWS
 24          24       thought         thing  2018   FIC
 25          25       thought         thing  2012  BLOG
 26          26       thought         thing  2012  BLOG
 27          27       thought         thing  2012  BLOG
 28          28          idea         thing  2015  SPOK
 29          29          idea         thing  2012   WEB
 30          30  relationship         thing  2012   WEB
 31          31  relationship         thing  2012   WEB
 32          32  relationship         thing  2012  BLOG
 33          33   opportunity           way  1996  SPOK
 34          34      quantity          size  2012  BLOG
 35          35        debate        combat  2008   FIC
 36          36        debate        combat  2007  SPOK

                        source  \
 0               ChurchHistory
 1                 CBS_Morning
 2                   NBC_Today
 3                 wikihow.com
 4         whereamiwearing.com
 5                 SouthernRev
 6            chriskresser.com
 7     ...eparty.wordpress.com
 8                   Parenting
 9          justsomelyrics.com
 10               NPR_FreshAir
 11                IntlAffairs
 12                 Wilderness
 13                   CNN_King
 14               CNN_Newsroom
 15                 amazon.com
 16             aintitcool.com
 17         NPR_TalkNation (1)
 18  Charles S. Peirce Society
 19         StudiesInEducation
 20               PBS_Newshour
 21    ...ytails.wordpress.com
 22              Bk:HemlockBay
 23                    Houston
 24                    Witness
 25    ...eoples.wordpress.com
 26    ...tart.bizjournals.com
 27    ...rystals.blogspot.com
 28              Fox: The Five
 29           thedailymind.com
 30         ask.metafilter.com
 31               abestweb.com
 32    ...lastpsychiatrist.com
 33                 CNN_Burden
 34    ...discovermagazine.com
 35                 ScholScope
 36              ABC_Nightline

                                                  text  \
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...
 12  People talk now about the timber in these fore...
 13  that capsule, you have close to a chance of a ...
 14  on the status of the thing, made aware of when...
 15  who were all the same and all they wanted to d...
 16  face-hugger and chestburster. The implication ...
 17  . And one thing that we're having to deal all ...
 18  separate things called emotions in it " (LW 10...
 19  . Unlike other forms of cognition, the things ...
 20  interior life of the narrator, especially, is ...
 21  n't what they seem,' or' I swear I just saw......
 22  . He just hoped it would continue the way it h...
 23  RHP Jason Bere, RHP Brian Williams, RHP Jim Br...
 24  had heard such a thing could happen, the mind ...
 25  both touch on the idea of thoughts creating re...
 26  some free ice cream. # They probably will once...
 27  with a hundred actions which lead to the circu...
 28  s the budget maven. Maybe he can do something....
 29  trouble over a tiny little calcification! # Li...
 30  , with that in mind: # It's important to me to...
 31  ). # Maybe what makes me feel as bad as anythi...
 32  play some role in this. You seem to want to ma...
 33  They need people that are doing that. And all ...
 34  distinct from other KBOs shifts the focus to q...
 35  is holding debate tryouts. Forty students cram...
 36  Wiley College taking on the national titans an...

                                            clean_text
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...
 12  People talk now about the timber in these fore...
 13  that capsule, you have close to a chance of a ...
 14  on the status of the thing, made aware of when...
 15  who were all the same and all they wanted to d...
 16  face-hugger and chestburster. The implication ...
 17  . And one thing that we're having to deal all ...
 18  separate things called emotions in it " (LW 10...
 19  . Unlike other forms of cognition, the things ...
 20  interior life of the narrator, especially, is ...
 21  n't what they seem,' or' I swear I just saw......
 22  . He just hoped it would continue the way it h...
 23  RHP Jason Bere, RHP Brian Williams, RHP Jim Br...
 24  had heard such a thing could happen, the mind ...
 25  both touch on the idea of thoughts creating re...
 26  some free ice cream. # They probably will once...
 27  with a hundred actions which lead to the circu...
 28  s the budget maven. Maybe he can do something....
 29  trouble over a tiny little calcification! # Li...
 30  , with that in mind: # It's important to me to...
 31  ). # Maybe what makes me feel as bad as anythi...
 32  play some role in this. You seem to want to ma...
 33  They need people that are doing that. And all ...
 34  distinct from other KBOs shifts the focus to q...
 35  is holding debate tryouts. Forty students cram...
 36  Wiley College taking on the national titans an...  ,
     Unnamed: 0       lemma_1       lemma_2  year genre  \
 0            0           act         place  2019   MAG
 1            1           act         place  2012   WEB
 2            2           act         place  1996  NEWS
 3            3        action         place  2012  BLOG
 4            4        action         place  2012  BLOG
 5            5        action         place  2002  NEWS
 6            6         actor         place  2012  SPOK
 7            7         actor         place  2005  ACAD
 8            8         actor      location  2016  NEWS
 9            9        action  neighborhood  2001   FIC
 10          10       thought          food  1992  SPOK
 11          11       capital         water  1991   MAG
 12          12         actor         speed  2005   FIC
 13          13          idea         thing  2012   WEB
 14          14          idea         thing  2012   WEB
 15          15  relationship         thing  1994  ACAD

                       source  \

In [65]:
import hashlib

def hashkey(x):
    return hashlib.md5(x.encode("utf-8")).hexdigest()

for i in orig_df:
    i['sentence_key'] = i['text'].apply(hashkey)

orig_df

[      Unnamed: 0   lemma_1  lemma_2  year genre                     source  \
 0              0  backward     time  2019   FIC                     Analog
 1              1  backward     time  2019  ACAD           Tehnicki Vjesnik
 2              2  backward     time  2017   MAG                    Nerdist
 3              3  backward     time  2012  ACAD               PhysicsToday
 4              4  backward     time  2012  ACAD               PhysicsToday
 ...          ...       ...      ...   ...   ...                        ...
 1789        1789      warm   caress  2009  NEWS                    Houston
 1790        1790      warm   caress  1996  SPOK               PBS_Newshour
 1791        1791      warm   caress  1995   FIC               FantasySciFi
 1792        1792      warm   caress  1994   MOV  That's Entertainment! III
 1793        1793      warm  snuggle  2012  BLOG    ...rstress.blogspot.com

                                                    text  \
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

                                              clean_text  \
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

                           sentence_key
 0     816c5fb126b4ea37f2d347fd59cfe27e
 1     d99fd3c45f8020c8888d004f8ca5bfea
 2     4eae9e7b36c4bba60eb912768bff2fc0
 3     a7eefd8fe53c8378c76cd4d89ad58f4e
 4     a9b7c8d7f4f9a0d6fa8f29ed3589d185
 ...                                ...
 1789  3a6d7c9a414bbc978fc8d8c2aebc1ca7
 1790  1e80b7e84dd2b467ea86998875e6b190
 1791  b25f5cee6141b819b4ec66b280fb45e6
 1792  dca7a8a0c6d811ceda8e4011817d260b
 1793  95017d9a9c9168291b22d499a048a50c

 [1794 rows x 9 columns],
       Unnamed: 0    lemma_1  lemma_2  year genre                   source  \
 0              0  difficult    catch  2019   MAG          Bleacher Report
 1              1  difficult    catch  2019  NEWS            Baltimore Sun
 2              2  difficult    catch  2018  NEWS        Chicago Sun-Times
 3              3  difficult    catch  2017  NEWS        Los Angeles Times
 4              4  difficult    catch  2012  BLOG       nflgridirongab.com
 ...          ...        ...      ...   ...   ...                      ...
 1515        1515    helpful  support  1992   MAG                Astronomy
 1516        1516      blind    touch  2008   FIC                   Poetry
 1517        1517      blind    touch  2000  SPOK                CNN_Event
 1518        1518      blind  feeling  2003  ACAD              PerspPolSci
 1519        1519  difficult   weight  2012   WEB  ...peare-literature.com

                                                    text  \
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

                                              clean_text  \
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

                           sentence_key
 0     9f3e159251fe76730c06dfeaa2497340
 1     21931213c266bec141cfe08d157d2797
 2     3f5033ed1246082bf65ccbed2dade5d3
 3     9ff4c7681de09113464915eea8db0ad9
 4     47d05fe8361efb235ecf37f999dba281
 ...                                ...
 1515  2a09c9471cd9120e212b1dd083adcc65
 1516  ba0e1d9f7adfa0ea471ea462fbec6cf3
 1517  356d862d4f6720798f9cb5688d7d8001
 1518  bf68bd0008334e18bed724dddd6840e0
 1519  8ec56a46abfcec611f66bb3e30d817f2

 [1520 rows x 9 columns],
      Unnamed: 0      lemma_1    lemma_2  year genre                   source  \
 0             0         back       time  2015   FIC             Ploughshares
 1             1         back       time  2012   WEB               amazon.com
 2             2         back       time  1990   FIC             VirginiaQRev
 3             3         area  existence  2012  BLOG  ...documentaryfilms.com
 4             4         area  existence  1996   FIC                   Tikkun
 ..          ...          ...        ...   ...   ...                      ...
 280         280       battle      point  1994  SPOK                  NPR_ATC
 281         281  battlefield     debate  2012  BLOG             theblaze.com
 282         282        blitz  criticism  2012   WEB                slate.com
 283         283   blitzkrieg  criticism  2009  SPOK                 CNN_Misc
 284         284          war   argument  2012  BLOG  ...rongwiththeworld.net

                                                   text  \
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

                                             clean_text  \
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

                          sentence_key
 0    a95ad482bd3dfc390610ad544cc98cfe
 1    6ea387591ace12569174cefd39a1b870
 2    c1c3470ef639329aefa1daf522e480a4
 3    a719464486e167bd6c1210940d5a0b38
 4    0d4e4ff3527c0a69db6e283d9455fb7b
 ..                                ...
 280  d0a0c9b864fa86ec23411ae08271f2e1
 281  552b26de9e0b082a868813157f5af769
 282  77c6b8684aaed34eea4c5b11df2efef2
 283  c2bd22dad0138271dd52ca348c4a9fa9
 284  1e810afa02c2b0e1cccbf311de6cc9bb

 [285 rows x 9 columns],
       Unnamed: 0     lemma_1    lemma_2  year genre                 source  \
 0              0        back       time  2018   MAG               Phys.Org
 1              1        back       time  2018   MAG       News-Medical.net
 2              2        back       time  2018   MAG   News-Medical.net (4)
 3              3        back       time  2017  NEWS  Chicago Sun-Times (3)
 4              4        back       time  2017    TV        Hap and Leonard
 ...          ...         ...        ...   ...   ...                    ...
 2074        2074       blitz  criticism  2012   WEB              slate.com
 2075        2075  blitzkrieg  criticism  2009  SPOK               CNN_Misc
 2076        2076       enemy     debate  2010   MAG             USCatholic
 2077        2077       troop      point  2012   WEB           shtfplan.com
 2078        2078      warmth        hug  2002   MAG              Parenting

                                                    text  \
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

                                              clean_text  \
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

                           sentence_key
 0     50164d2fcb686200b8431b9ecbfc4b19
 1     b57d22c3a50e7df9bb15e61133bb7a97
 2     f5967b7409b7997f5906554d5925fdce
 3     bf6275b3bf0a934f09b6f24a180b778d
 4     594a529b9eaae87f6b96cafa952dedba
 ...                                ...
 2074  b10ce4e59d2a843154edda5de9627b4c
 2075  0ac97e27e0fccd64de262b25c8a0a87b
 2076  cefdd0498f4ffccbc3683779f27f584f
 2077  ed8c20c093eb0dfebe740ffebaf51257
 2078  f043b10c27491b33cd2e69324a4d4f4c

 [2079 rows x 9 columns],
     Unnamed: 0   lemma_1    lemma_2  year genre                   source  \
 0            0     power  expansive  2004  ACAD              Environment
 1            1   feeling       hurt  2018   FIC             Ploughshares
 2            2   feeling       hurt  2012   WEB              squidoo.com
 3            3   feeling       hurt  2012  BLOG          firebrandal.com
 4            4   feeling       hurt  2012  BLOG  ...ekgirl.wordpress.com
 ..         ...       ...        ...   ...   ...                      ...
 89          89  quantity       tiny  2012  BLOG      investinmiskolc.com
 90          90   control   vertical  1993  SPOK              CBS_Morning
 91          91      kiss       warm  2006   FIC                  Redbook
 92          92      kiss       warm  2005   MAG             Cosmopolitan
 93          93      kiss       warm  1999   FIC             Cosmopolitan

                                                  text  \
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

                                            clean_text  \
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

                         sentence_key
 0   ab5ead69aa0623d339286eb90ccf2932
 1   3e17aecd4cd1cae4d32f56f0365ec7db
 2   fdc449bdcc9fd61030d4f5f06b769b99
 3   9368adcc1037d308ff58f117e5d61d3d
 4   7928f7bdb8dd180f8f9bfb782013e91d
 ..                               ...
 89  092fb9c43ac80aeb14bf058b0f6e9f1b
 90  5dd01bb605ebe97a976a428680fe8c86
 91  09efc546a75f9690b97576dee893a2fe
 92  c6df7182002fd6c3887eba5d2f336a4b
 93  8eb2956cd2675554867d5d62676a45f7

 [94 rows x 9 columns],
     Unnamed: 0       lemma_1       lemma_2  year genre  \
 0            0          time      location  2004  ACAD
 1            1          time  neighborhood  2005  SPOK
 2            2          idea          food  2018  SPOK
 3            3          idea          food  2012   WEB
 4            4          idea         sugar  2012  BLOG
 5            5       thought          food  2019   FIC
 6            6         cause          food  2012  BLOG
 7            7         cause          food  2012  BLOG
 8            8         cause          food  2006   MAG
 9            9        desire        hunger  2012   WEB
 10          10        desire        hunger  2010  SPOK
 11          11      resource         water  1998  ACAD
 12          12      resource         water  1990   MAG
 13          13       feeling            go  2000  SPOK
 14          14          time            go  2017  SPOK
 15          15          time            go  2012   WEB
 16          16          time            go  2012  BLOG
 17          17          time            go  2011  SPOK
 18          18       emotion         thing  2016  ACAD
 19          19       emotion         thing  2014  ACAD
 20          20       emotion         thing  2012  SPOK
 21          21        chance         thing  2012  BLOG
 22          22        chance         thing  2002   FIC
 23          23        chance         thing  2001  NEWS
 24          24       thought         thing  2018   FIC
 25          25       thought         thing  2012  BLOG
 26          26       thought         thing  2012  BLOG
 27          27       thought         thing  2012  BLOG
 28          28          idea         thing  2015  SPOK
 29          29          idea         thing  2012   WEB
 30          30  relationship         thing  2012   WEB
 31          31  relationship         thing  2012   WEB
 32          32  relationship         thing  2012  BLOG
 33          33   opportunity           way  1996  SPOK
 34          34      quantity          size  2012  BLOG
 35          35        debate        combat  2008   FIC
 36          36        debate        combat  2007  SPOK

                        source  \
 0               ChurchHistory
 1                 CBS_Morning
 2                   NBC_Today
 3                 wikihow.com
 4         whereamiwearing.com
 5                 SouthernRev
 6            chriskresser.com
 7     ...eparty.wordpress.com
 8                   Parenting
 9          justsomelyrics.com
 10               NPR_FreshAir
 11                IntlAffairs
 12                 Wilderness
 13                   CNN_King
 14               CNN_Newsroom
 15                 amazon.com
 16             aintitcool.com
 17         NPR_TalkNation (1)
 18  Charles S. Peirce Society
 19         StudiesInEducation
 20               PBS_Newshour
 21    ...ytails.wordpress.com
 22              Bk:HemlockBay
 23                    Houston
 24                    Witness
 25    ...eoples.wordpress.com
 26    ...tart.bizjournals.com
 27    ...rystals.blogspot.com
 28              Fox: The Five
 29           thedailymind.com
 30         ask.metafilter.com
 31               abestweb.com
 32    ...lastpsychiatrist.com
 33                 CNN_Burden
 34    ...discovermagazine.com
 35                 ScholScope
 36              ABC_Nightline

                                                  text  \
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...
 12  People talk now about the timber in these fore...
 13  that capsule, you have close to a chance of a ...
 14  on the status of the thing, made aware of when...
 15  who were all the same and all they wanted to d...
 16  face-hugger and chestburster. The implication ...
 17  . And one thing that we're having to deal all ...
 18  separate things called emotions in it " (LW 10...
 19  . Unlike other forms of cognition, the things ...
 20  interior life of the narrator, especially, is ...
 21  n't what they seem,' or' I swear I just saw......
 22  . He just hoped it would continue the way it h...
 23  RHP Jason Bere, RHP Brian Williams, RHP Jim Br...
 24  had heard such a thing could happen, the mind ...
 25  both touch on the idea of thoughts creating re...
 26  some free ice cream. # They probably will once...
 27  with a hundred actions which lead to the circu...
 28  s the budget maven. Maybe he can do something....
 29  trouble over a tiny little calcification! # Li...
 30  , with that in mind: # It's important to me to...
 31  ). # Maybe what makes me feel as bad as anythi...
 32  play some role in this. You seem to want to ma...
 33  They need people that are doing that. And all ...
 34  distinct from other KBOs shifts the focus to q...
 35  is holding debate tryouts. Forty students cram...
 36  Wiley College taking on the national titans an...

                                            clean_text  \
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...

In [69]:
for i in orig_df:
    i = i.drop_duplicates(subset="sentence_key")

    print(i.sentence_key.value_counts())

for name, df in zip(file_names, orig_df):
    df.to_csv(f"data/processed/main/tmp/{name}.csv", index=False)

sentence_key
816c5fb126b4ea37f2d347fd59cfe27e    1
f5080daa1fef7f4153d9527c4bacd643    1
7900f9e867059747dc7aa3a7fc137bf2    1
5ab1a89af6d072b65a1735030399b185    1
0d42d5b02d2f64c988b7662f2c56c10d    1
                                   ..
785959c6de8410f4e918e5f10075b7b1    1
73ebcb3783bc4019654045b05d3f24bf    1
4a264d5536ae3279934ce6e9aba14731    1
904759712cb121e66932a62f705b0f62    1
95017d9a9c9168291b22d499a048a50c    1
Name: count, Length: 1782, dtype: int64
sentence_key
9f3e159251fe76730c06dfeaa2497340    1
008f86818fe8f35ec03a12c70a045e19    1
501fb4a7f456eb2c2438b076f20b0a0e    1
124f8d03e2ad3dfb5618a7c0e56d3abe    1
aee562f314399d4442b39f0bf2d8e8e7    1
                                   ..
4cd0b271ae639c001c78582300dd1c09    1
f2e72a1436f9ca86367a4849b132fff0    1
3ae8c80015039a4954a4d21103edba44    1
42b0b3142c121feae4ada2d5ee7888fe    1
8ec56a46abfcec611f66bb3e30d817f2    1
Name: count, Length: 1458, dtype: int64
sentence_key
a95ad482bd3dfc390610ad544cc98cfe    1
5f6e2422f9708c1bdffa59828a7ebbd0    1
1eed4450a5305123c5659aa820c360d6    1
4a0c44da58d5ec9dad40b3ab4676e95b    1
81a59bae1177980b042b46076bf3d2c5    1
                                   ..
965ff5dd6e2eb6ecf12ce6f2aeeeaebf    1
154dbf5b802d79f62e632191479d5c86    1
5b6631e27e0ac0174592bbf2fb3bf06e    1
e4476133635ba3950fa4f29dc678e696    1
1e810afa02c2b0e1cccbf311de6cc9bb    1
Name: count, Length: 275, dtype: int64
sentence_key
50164d2fcb686200b8431b9ecbfc4b19    1
e35e39508e6086c4b9305705373b3a05    1
dde99d8e123d6cb8e8e5ce767293fff3    1
4cc6012e674969433b44e7737b0d6e44    1
6f859faf90d06b7cdea380a7c6eaedb8    1
                                   ..
67d9be848e9a41a920e81062dd2b4e36    1
d8e6c1d0bf3da9c4e77e3567b4a60f3c    1
c2216bee10b8a137425c7576d30ac15e    1
607dce31736bf95ac14d85d38bda091c    1
f043b10c27491b33cd2e69324a4d4f4c    1
Name: count, Length: 2066, dtype: int64
sentence_key
ab5ead69aa0623d339286eb90ccf2932    1
0c9d7f560a7a50693ad75cbb03dbb19b    1
1d846e2f302be7d556b5ec3b2410fa0a    1
fbf76b4e20375e907480f59b4fb672a3    1
9b7cf1484d880df7d2214174ba8ee70e    1
                                   ..
54537eb77bd6d5794f9b5c25a00efe02    1
599f024a0df26b528ff16ac5130fca3a    1
f3f1dd6665b3e6f996191e5db2a10818    1
91418835358da9d24272f286e2fe84c7    1
8eb2956cd2675554867d5d62676a45f7    1
Name: count, Length: 84, dtype: int64
sentence_key
ba8766f0c84ec64f89b41b92ab1fa5b7    1
61e704d1715de6dae1f9929d344d06b1    1
de195d20c7a4ee924a2f84c9ce1e0190    1
aab36dec094d861134f02053f97ff319    1
701d644fb8bb1228569fb4f6b8ac76fe    1
e308126441b3862bd61e1254b88fe035    1
d6875bd7ea969f03cb96f8b1f7e9143d    1
87031a47f790bd600a4b5af9beaf5f9c    1
f173bf4ff10f83761d7c85da67d93929    1
c1ef3a1c833bb0dfdc11b38e58450755    1
0d1286854ed200d26e95e4def6b4308f    1
33910015a8ba7e5916ad52d19c9612df    1
b9016e9b0eb40b4f67ce62a90e18b7de    1
f36f5e5d3f7d2e505e13786204efd391    1
76ae4b385db7c5039bb8016782cc91f5    1
16e664d31590e6fee145a54d30315421    1
7ffddfda51068941b2545854c6b55976    1
1a88fa0aa0a3070275d1c24005965d57    1
a7f6eceb91e5259bb288f85957cd7f28    1
eaf87024d551feba40c3009e54aac54e    1
225a4b8bd721dc3300c4016e7159ab3d    1
93aa7bbd3e75d45e99d6aed3385399f5    1
6b832a551340904fd9cdc93152f78840    1
a0cfc302f2246d166f370b303203e663    1
d9083cb0da207028c771bad2911e77ad    1
4cca816f36f61590d187af6532f6fe54    1
36fce025d9bfe7ea56a5d3796344bf02    1
8269ffd4a5ba0589a4a7472cd0c3cb16    1
224c178f36107f1dd11bb85044e4db59    1
fd5a41ca901d3110335fc3a70d749732    1
ad5c32e1dd8694c8466ae2a87c648a5c    1
6fa643cb30b978d413ae6416b71d8753    1
e4e6155be261fb014ca47ea1fca8ab53    1
8220e60b0d8c5341cb79d675bcd72822    1
54bd36c6b682896469ef83aead2d1675    1
653a83b7a73b72c1f3e3a93a6e475fed    1
bb0c6e91d84839c8d2c086212d473d2a    1
Name: count, dtype: int64
sentence_key
5c740fa80d8501d2bce1539f7d0ea008    1
d02221c1ebddcb2cc7d8dd80ddb3a27f    1
28628bf993dc18b0a716805b4f0e579f    1
b3b2182607ae699640d8c08b3a956505    1
755e353a995ae8f3971547821219c311    1
bb9b4fa91132e4c81bddaff61e960c14    1
ec0fc7203b3dc9d38c4c2db7b0cf4187    1
cd19d564564854e8d92d9c72757aff03    1
50f8ba1c6b5430e8bf8c795a50696e5f    1
1154fa879cc2df84874a604e50e6a3d7    1
46469dfb4dc099ea415d57db7d50f4ad    1
70876b795381a1c1cd0490573a8c544c    1
57038b28f83ca4a3831ca79ef32b9d61    1
aa611a0a1d234fe76084125fa1281e56    1
9eeb3aae9ffa82481e1535c1a045509b    1
9724a1b1817d1c572a3c981fa5affb63    1
Name: count, dtype: int64
sentence_key
9c2d90387cfb60692dfe14229b611cc5    1
0162532d962e50fb88bfbd94af88bb6a    1
c50a31166f5fd667739b4feef72da90d    1
1c8074a89cc383880613492257f0eaf3    1
4738ba783ca2ec7bd8153aa8f4834607    1
                                   ..
1c5b045417d75dbafcf5cada1c60c89f    1
aee147b0dc14dda469ae449c7f50e250    1
8f3135e54802f075f2383ffa4f816492    1
3a1567195faa68aee5c84cd496c6387b    1
ac17e6d0352f31f7f97667cf95369add    1
Name: count, Length: 1038, dtype: int64
sentence_key
9a98da31a99e90b1a976899931cadbcf    1
a5f8502a2b660d7df9784d014d2726ec    1
aef6e0749d0a6abcec17b8f9c984e3e5    1
30779a18ea05eed333c1988f9e246560    1
aebd0a807d76a455ffd03fa2897a1216    1
                                   ..
0b7eb55072a07df743510346bdac2d0d    1
fd29860e4b537b50bde7de49392f7ba2    1
79a88e10afd2c563bec4907d49783308    1
47024d68da908185f29ff849fabc6928    1
527cbb99bb7b0ee4d98787011a7f0fc5    1
Name: count, Length: 3036, dtype: int64
sentence_key
8d9e515ed24c9d6f03d696b0df73b659    1
d2d86ed011bfc2759a7525e79187f0c5    1
f6816bef3a2ff6d695b42f115a9b4293    1
6ffb9d0d0dbcdd6df80ec8b5c37a719e    1
7e1e35990b39e800aa4fa50352999439    1
                                   ..
d3f2893d76803d12af266b44b9a2a872    1
f1a55871c2ea8ace9cfdbc6ff98b3731    1
e246d0e62a98700f5b7f4f4ac85e6660    1
cb84f1ab5c9b2d26e921158ad0922e4e    1
4058475c62f8e0704f338b08ed74cc7f    1
Name: count, Length: 894, dtype: int64

In [3]:
tmp_hashed = []
for name in file_names:
    f = pd.read_csv(f"data/processed/main/tmp/{name}.csv")
    tmp_hashed.append(f)
tmp_hashed

[      Unnamed: 0   lemma_1  lemma_2  year genre                     source  \
 0              0  backward     time  2019   FIC                     Analog
 1              1  backward     time  2019  ACAD           Tehnicki Vjesnik
 2              2  backward     time  2017   MAG                    Nerdist
 3              3  backward     time  2012  ACAD               PhysicsToday
 4              4  backward     time  2012  ACAD               PhysicsToday
 ...          ...       ...      ...   ...   ...                        ...
 1789        1789      warm   caress  2009  NEWS                    Houston
 1790        1790      warm   caress  1996  SPOK               PBS_Newshour
 1791        1791      warm   caress  1995   FIC               FantasySciFi
 1792        1792      warm   caress  1994   MOV  That's Entertainment! III
 1793        1793      warm  snuggle  2012  BLOG    ...rstress.blogspot.com

                                                    text  \
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

                                              clean_text  \
 0     too-forward. Maybe the only allowed way; no pa...
 1     There are three general approaches to detectin...
 2     was born to play. She's outspoken and feminist...
 3     are locally the regions of most strongly diver...
 4     one identifies regions with high backward-time...
 ...                                                 ...
 1789  than height): The Leprechaun, grille # Sample ...
 1790  Blizzard is freezing toes and frosting noses u...
 1791  into heavy-limbed paralysis: it was impossible...
 1792  plans Just little pots and pans In the doorway...
 1793  tonight for the first time. # There are things...

                           sentence_key
 0     816c5fb126b4ea37f2d347fd59cfe27e
 1     d99fd3c45f8020c8888d004f8ca5bfea
 2     4eae9e7b36c4bba60eb912768bff2fc0
 3     a7eefd8fe53c8378c76cd4d89ad58f4e
 4     a9b7c8d7f4f9a0d6fa8f29ed3589d185
 ...                                ...
 1789  3a6d7c9a414bbc978fc8d8c2aebc1ca7
 1790  1e80b7e84dd2b467ea86998875e6b190
 1791  b25f5cee6141b819b4ec66b280fb45e6
 1792  dca7a8a0c6d811ceda8e4011817d260b
 1793  95017d9a9c9168291b22d499a048a50c

 [1794 rows x 9 columns],
       Unnamed: 0    lemma_1  lemma_2  year genre                   source  \
 0              0  difficult    catch  2019   MAG          Bleacher Report
 1              1  difficult    catch  2019  NEWS            Baltimore Sun
 2              2  difficult    catch  2018  NEWS        Chicago Sun-Times
 3              3  difficult    catch  2017  NEWS        Los Angeles Times
 4              4  difficult    catch  2012  BLOG       nflgridirongab.com
 ...          ...        ...      ...   ...   ...                      ...
 1515        1515    helpful  support  1992   MAG                Astronomy
 1516        1516      blind    touch  2008   FIC                   Poetry
 1517        1517      blind    touch  2000  SPOK                CNN_Event
 1518        1518      blind  feeling  2003  ACAD              PerspPolSci
 1519        1519  difficult   weight  2012   WEB  ...peare-literature.com

                                                    text  \
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

                                              clean_text  \
 0     As Brian Baldinger of NFL.com pointed out, it ...
 1     , with Trey Mancini going back to the warning ...
 2     a receiver. Big hands, great footwork and a kn...
 3     # With Tavon Austin sidelined while recovering...
 4     his potential offensively (his hands are not r...
 ...                                                 ...
 1515  me how to use the spectrometer and the new com...
 1516  pen or chiseling with a typewriter, was physic...
 1517  a pair, who's getting hose? Though the expensi...
 1518  they are general. So, experiencing them can no...
 1519  mean to touch your love indeed, It shall be fu...

                           sentence_key
 0     9f3e159251fe76730c06dfeaa2497340
 1     21931213c266bec141cfe08d157d2797
 2     3f5033ed1246082bf65ccbed2dade5d3
 3     9ff4c7681de09113464915eea8db0ad9
 4     47d05fe8361efb235ecf37f999dba281
 ...                                ...
 1515  2a09c9471cd9120e212b1dd083adcc65
 1516  ba0e1d9f7adfa0ea471ea462fbec6cf3
 1517  356d862d4f6720798f9cb5688d7d8001
 1518  bf68bd0008334e18bed724dddd6840e0
 1519  8ec56a46abfcec611f66bb3e30d817f2

 [1520 rows x 9 columns],
      Unnamed: 0      lemma_1    lemma_2  year genre                   source  \
 0             0         back       time  2015   FIC             Ploughshares
 1             1         back       time  2012   WEB               amazon.com
 2             2         back       time  1990   FIC             VirginiaQRev
 3             3         area  existence  2012  BLOG  ...documentaryfilms.com
 4             4         area  existence  1996   FIC                   Tikkun
 ..          ...          ...        ...   ...   ...                      ...
 280         280       battle      point  1994  SPOK                  NPR_ATC
 281         281  battlefield     debate  2012  BLOG             theblaze.com
 282         282        blitz  criticism  2012   WEB                slate.com
 283         283   blitzkrieg  criticism  2009  SPOK                 CNN_Misc
 284         284          war   argument  2012  BLOG  ...rongwiththeworld.net

                                                   text  \
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

                                             clean_text  \
 0    #upon you; it did not help, this turning back ...
 1    #revealed. # In a supreme irony, the folding b...
 2    #is very nice, how you get up on the back of t...
 3    #. Perhapse science will evolve beyond the kno...
 4    #only semi-voluntarily, placed this man in an ...
 ..                                                 ...
 280  #wars going all the way back to the Battle of ...
 281  #are ones who look foolish, engage the battlef...
 282  #and in some cases preemptively, with a blitz ...
 283  #. MESERVE: On Capitol Hill a Republican blitz...
 284  #the Big Texter in the sky? In war of argument...

                          sentence_key
 0    a95ad482bd3dfc390610ad544cc98cfe
 1    6ea387591ace12569174cefd39a1b870
 2    c1c3470ef639329aefa1daf522e480a4
 3    a719464486e167bd6c1210940d5a0b38
 4    0d4e4ff3527c0a69db6e283d9455fb7b
 ..                                ...
 280  d0a0c9b864fa86ec23411ae08271f2e1
 281  552b26de9e0b082a868813157f5af769
 282  77c6b8684aaed34eea4c5b11df2efef2
 283  c2bd22dad0138271dd52ca348c4a9fa9
 284  1e810afa02c2b0e1cccbf311de6cc9bb

 [285 rows x 9 columns],
       Unnamed: 0     lemma_1    lemma_2  year genre                 source  \
 0              0        back       time  2018   MAG               Phys.Org
 1              1        back       time  2018   MAG       News-Medical.net
 2              2        back       time  2018   MAG   News-Medical.net (4)
 3              3        back       time  2017  NEWS  Chicago Sun-Times (3)
 4              4        back       time  2017    TV        Hap and Leonard
 ...          ...         ...        ...   ...   ...                    ...
 2074        2074       blitz  criticism  2012   WEB              slate.com
 2075        2075  blitzkrieg  criticism  2009  SPOK               CNN_Misc
 2076        2076       enemy     debate  2010   MAG             USCatholic
 2077        2077       troop      point  2012   WEB           shtfplan.com
 2078        2078      warmth        hug  2002   MAG              Parenting

                                                    text  \
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

                                              clean_text  \
 0     the past. Credit: Caitlyn Witkowski # Earth sc...
 1     former colleagues who wanted to create virtual...
 2     colleagues who wanted to create virtual realit...
 3     the very least, his teammates respect his appr...
 4     I lay eyes on him. Why do I feel like I'm goin...
 ...                                                 ...
 2074  -- was met quickly, and in some cases preempti...
 2075  around the world is eliminated. MESERVE: On Ca...
 2076  other as enemies. The other lesson is probably...
 2077  # How do you institute martial law if you can'...
 2078  child. For a very young child, feeling love is...

                           sentence_key
 0     50164d2fcb686200b8431b9ecbfc4b19
 1     b57d22c3a50e7df9bb15e61133bb7a97
 2     f5967b7409b7997f5906554d5925fdce
 3     bf6275b3bf0a934f09b6f24a180b778d
 4     594a529b9eaae87f6b96cafa952dedba
 ...                                ...
 2074  b10ce4e59d2a843154edda5de9627b4c
 2075  0ac97e27e0fccd64de262b25c8a0a87b
 2076  cefdd0498f4ffccbc3683779f27f584f
 2077  ed8c20c093eb0dfebe740ffebaf51257
 2078  f043b10c27491b33cd2e69324a4d4f4c

 [2079 rows x 9 columns],
     Unnamed: 0   lemma_1    lemma_2  year genre                   source  \
 0            0     power  expansive  2004  ACAD              Environment
 1            1   feeling       hurt  2018   FIC             Ploughshares
 2            2   feeling       hurt  2012   WEB              squidoo.com
 3            3   feeling       hurt  2012  BLOG          firebrandal.com
 4            4   feeling       hurt  2012  BLOG  ...ekgirl.wordpress.com
 ..         ...       ...        ...   ...   ...                      ...
 89          89  quantity       tiny  2012  BLOG      investinmiskolc.com
 90          90   control   vertical  1993  SPOK              CBS_Morning
 91          91      kiss       warm  2006   FIC                  Redbook
 92          92      kiss       warm  2005   MAG             Cosmopolitan
 93          93      kiss       warm  1999   FIC             Cosmopolitan

                                                  text  \
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

                                            clean_text  \
 0   between the two: Nuclear power is compact and ...
 1   like a lover in a movie. When he didn't, her f...
 2   . Doing things apart helps you to appreciate o...
 3   to give Chip a little bit different perspectiv...
 4   n't a geek! # I didn't mean to imply that my f...
 ..                                                ...
 89  under consideration are merely huge. But unsec...
 90  women are actually less comfortable lying hori...
 91  before leaning over to kiss me. " Mappy birthd...
 92  , pulls back and smiles, then leans in again f...
 93  her. His lips were full and sensual and delive...

                         sentence_key
 0   ab5ead69aa0623d339286eb90ccf2932
 1   3e17aecd4cd1cae4d32f56f0365ec7db
 2   fdc449bdcc9fd61030d4f5f06b769b99
 3   9368adcc1037d308ff58f117e5d61d3d
 4   7928f7bdb8dd180f8f9bfb782013e91d
 ..                               ...
 89  092fb9c43ac80aeb14bf058b0f6e9f1b
 90  5dd01bb605ebe97a976a428680fe8c86
 91  09efc546a75f9690b97576dee893a2fe
 92  c6df7182002fd6c3887eba5d2f336a4b
 93  8eb2956cd2675554867d5d62676a45f7

 [94 rows x 9 columns],
     Unnamed: 0       lemma_1       lemma_2  year genre  \
 0            0          time      location  2004  ACAD
 1            1          time  neighborhood  2005  SPOK
 2            2          idea          food  2018  SPOK
 3            3          idea          food  2012   WEB
 4            4          idea         sugar  2012  BLOG
 5            5       thought          food  2019   FIC
 6            6         cause          food  2012  BLOG
 7            7         cause          food  2012  BLOG
 8            8         cause          food  2006   MAG
 9            9        desire        hunger  2012   WEB
 10          10        desire        hunger  2010  SPOK
 11          11      resource         water  1998  ACAD
 12          12      resource         water  1990   MAG
 13          13       feeling            go  2000  SPOK
 14          14          time            go  2017  SPOK
 15          15          time            go  2012   WEB
 16          16          time            go  2012  BLOG
 17          17          time            go  2011  SPOK
 18          18       emotion         thing  2016  ACAD
 19          19       emotion         thing  2014  ACAD
 20          20       emotion         thing  2012  SPOK
 21          21        chance         thing  2012  BLOG
 22          22        chance         thing  2002   FIC
 23          23        chance         thing  2001  NEWS
 24          24       thought         thing  2018   FIC
 25          25       thought         thing  2012  BLOG
 26          26       thought         thing  2012  BLOG
 27          27       thought         thing  2012  BLOG
 28          28          idea         thing  2015  SPOK
 29          29          idea         thing  2012   WEB
 30          30  relationship         thing  2012   WEB
 31          31  relationship         thing  2012   WEB
 32          32  relationship         thing  2012  BLOG
 33          33   opportunity           way  1996  SPOK
 34          34      quantity          size  2012  BLOG
 35          35        debate        combat  2008   FIC
 36          36        debate        combat  2007  SPOK

                        source  \
 0               ChurchHistory
 1                 CBS_Morning
 2                   NBC_Today
 3                 wikihow.com
 4         whereamiwearing.com
 5                 SouthernRev
 6            chriskresser.com
 7     ...eparty.wordpress.com
 8                   Parenting
 9          justsomelyrics.com
 10               NPR_FreshAir
 11                IntlAffairs
 12                 Wilderness
 13                   CNN_King
 14               CNN_Newsroom
 15                 amazon.com
 16             aintitcool.com
 17         NPR_TalkNation (1)
 18  Charles S. Peirce Society
 19         StudiesInEducation
 20               PBS_Newshour
 21    ...ytails.wordpress.com
 22              Bk:HemlockBay
 23                    Houston
 24                    Witness
 25    ...eoples.wordpress.com
 26    ...tart.bizjournals.com
 27    ...rystals.blogspot.com
 28              Fox: The Five
 29           thedailymind.com
 30         ask.metafilter.com
 31               abestweb.com
 32    ...lastpsychiatrist.com
 33                 CNN_Burden
 34    ...discovermagazine.com
 35                 ScholScope
 36              ABC_Nightline

                                                  text  \
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...
 12  People talk now about the timber in these fore...
 13  that capsule, you have close to a chance of a ...
 14  on the status of the thing, made aware of when...
 15  who were all the same and all they wanted to d...
 16  face-hugger and chestburster. The implication ...
 17  . And one thing that we're having to deal all ...
 18  separate things called emotions in it " (LW 10...
 19  . Unlike other forms of cognition, the things ...
 20  interior life of the narrator, especially, is ...
 21  n't what they seem,' or' I swear I just saw......
 22  . He just hoped it would continue the way it h...
 23  RHP Jason Bere, RHP Brian Williams, RHP Jim Br...
 24  had heard such a thing could happen, the mind ...
 25  both touch on the idea of thoughts creating re...
 26  some free ice cream. # They probably will once...
 27  with a hundred actions which lead to the circu...
 28  s the budget maven. Maybe he can do something....
 29  trouble over a tiny little calcification! # Li...
 30  , with that in mind: # It's important to me to...
 31  ). # Maybe what makes me feel as bad as anythi...
 32  play some role in this. You seem to want to ma...
 33  They need people that are doing that. And all ...
 34  distinct from other KBOs shifts the focus to q...
 35  is holding debate tryouts. Forty students cram...
 36  Wiley College taking on the national titans an...

                                            clean_text  \
 0   before the locomotive age " universal time " d...
 1   from the first. Ms-PARKER: (Voiceover) The Sou...
 2   it's too cute. HODA-KOTB) : Here with some of ...
 3   your movie night. # 2 # Ensure that you have s...
 4   giving a free pair of shoes to someone in pove...
 5   s what I did, until Ann got sick. # My first t...
 6   WELL. # My thinking is that being obese is not...
 7   . The mess in the house is increasing as well,...
 8   important to call if you have a baby under 1 w...
 9   now baby here as I am pull me close, try and u...
 10  here as I am. Pull me close, try and understan...
 11  that battles over resource scarcities will oth...

In [4]:
for file in tmp_hashed:
    print(file.clean_text)

0       too-forward. Maybe the only allowed way; no pa...
1       There are three general approaches to detectin...
2       was born to play. She's outspoken and feminist...
3       are locally the regions of most strongly diver...
4       one identifies regions with high backward-time...
                              ...
1789    than height): The Leprechaun, grille # Sample ...
1790    Blizzard is freezing toes and frosting noses u...
1791    into heavy-limbed paralysis: it was impossible...
1792    plans Just little pots and pans In the doorway...
1793    tonight for the first time. # There are things...
Name: clean_text, Length: 1794, dtype: object
0       As Brian Baldinger of NFL.com pointed out, it ...
1       , with Trey Mancini going back to the warning ...
2       a receiver. Big hands, great footwork and a kn...
3       # With Tavon Austin sidelined while recovering...
4       his potential offensively (his hands are not r...
                              ...
1515    me how to use the spectrometer and the new com...
1516    pen or chiseling with a typewriter, was physic...
1517    a pair, who's getting hose? Though the expensi...
1518    they are general. So, experiencing them can no...
1519    mean to touch your love indeed, It shall be fu...
Name: clean_text, Length: 1520, dtype: object
0      #upon you; it did not help, this turning back ...
1      #revealed. # In a supreme irony, the folding b...
2      #is very nice, how you get up on the back of t...
3      #. Perhapse science will evolve beyond the kno...
4      #only semi-voluntarily, placed this man in an ...
                             ...
280    #wars going all the way back to the Battle of ...
281    #are ones who look foolish, engage the battlef...
282    #and in some cases preemptively, with a blitz ...
283    #. MESERVE: On Capitol Hill a Republican blitz...
284    #the Big Texter in the sky? In war of argument...
Name: clean_text, Length: 285, dtype: object
0       the past. Credit: Caitlyn Witkowski # Earth sc...
1       former colleagues who wanted to create virtual...
2       colleagues who wanted to create virtual realit...
3       the very least, his teammates respect his appr...
4       I lay eyes on him. Why do I feel like I'm goin...
                              ...
2074    -- was met quickly, and in some cases preempti...
2075    around the world is eliminated. MESERVE: On Ca...
2076    other as enemies. The other lesson is probably...
2077    # How do you institute martial law if you can'...
2078    child. For a very young child, feeling love is...
Name: clean_text, Length: 2079, dtype: object
0     between the two: Nuclear power is compact and ...
1     like a lover in a movie. When he didn't, her f...
2     . Doing things apart helps you to appreciate o...
3     to give Chip a little bit different perspectiv...
4     n't a geek! # I didn't mean to imply that my f...
                            ...
89    under consideration are merely huge. But unsec...
90    women are actually less comfortable lying hori...
91    before leaning over to kiss me. " Mappy birthd...
92    , pulls back and smiles, then leans in again f...
93    her. His lips were full and sensual and delive...
Name: clean_text, Length: 94, dtype: object
0     before the locomotive age " universal time " d...
1     from the first. Ms-PARKER: (Voiceover) The Sou...
2     it's too cute. HODA-KOTB) : Here with some of ...
3     your movie night. # 2 # Ensure that you have s...
4     giving a free pair of shoes to someone in pove...
5     s what I did, until Ann got sick. # My first t...
6     WELL. # My thinking is that being obese is not...
7     . The mess in the house is increasing as well,...
8     important to call if you have a baby under 1 w...
9     now baby here as I am pull me close, try and u...
10    here as I am. Pull me close, try and understan...
11    that battles over resource scarcities will oth...
12    People talk now about the timber in these fore...
13    that capsule, you have close to a chance of a ...
14    on the status of the thing, made aware of when...
15    who were all the same and all they wanted to d...
16    face-hugger and chestburster. The implication ...
17    . And one thing that we're having to deal all ...
18    separate things called emotions in it " (LW 10...
19    . Unlike other forms of cognition, the things ...
20    interior life of the narrator, especially, is ...
21    n't what they seem,' or' I swear I just saw......
22    . He just hoped it would continue the way it h...
23    RHP Jason Bere, RHP Brian Williams, RHP Jim Br...
24    had heard such a thing could happen, the mind ...
25    both touch on the idea of thoughts creating re...
26    some free ice cream. # They probably will once...
27    with a hundred actions which lead to the circu...
28    s the budget maven. Maybe he can do something....
29    trouble over a tiny little calcification! # Li...
30    , with that in mind: # It's important to me to...
31    ). # Maybe what makes me feel as bad as anythi...
32    play some role in this. You seem to want to ma...
33    They need people that are doing that. And all ...
34    distinct from other KBOs shifts the focus to q...
35    is holding debate tryouts. Forty students cram...
36    Wiley College taking on the national titans an...
Name: clean_text, dtype: object
0     system shouldn't depend on luck, " Charles wro...
1     the end of the article. Her argument is essent...
2     repealed until 1943. # " They felt they solved...
3     the privilege they are afforded because its so...
4     and the environmental engineers from the city ...
5     said. # He was admitted to UC Berkeley in the ...
6     " What Would You Do? " The cameras and microph...
7     retention of special education teachers for ru...
8     to flee in the middle of the night, never to r...
9     the clean, white-bread streets of upper Northw...
10    s Charlie Murphy. CHARLES MURPHY: BOSTON ROAD ...
11    . Automatic gunfire was almost continuous arou...
12    theater for the first time said it seemed as i...
13    to put it into words.... It is spectacle and e...
14    too much emphasis was placed on exercise throu...
15    venerable role of Igbo priest and artist. # Ac...
Name: clean_text, dtype: object
0       sorry to disappoint you. Dr. Dillman, was ther...
1       of two boys. One is only four -- BRIT-MORIN# T...
2       hoped to intercede as little as possible. Logi...
3       range and stabbed while driving, both times by...
4       s political views). I remember listening to a ...
                              ...
1035    profile you, spin you or lurk in your shrubber...
1036    Institute in partnership with the St. Mark's S...
1037    the world's most pre-eminent debater, a man wh...
1038    The lead story was headlined " Thousands Prote...
1039    is the web host to these matter of fact Islami...
Name: clean_text, Length: 1040, dtype: object
0       Some children enter kindergarten with few earl...
1       . Mets starter R.A. Dickey seemed like the obv...
2       s ability to walk in a straight line was somew...
3       at least 80 percent of attacks. This indicates...
4       subtle... FLATOW: Right. Dr-KARAS:... and can ...
                              ...
3046    directly in your inbox. 8565424 Islamic State ...
3047    Soon, " he said, before disappearing down the ...
3048    commanding terrain to block the road between P...
3049    her. Every girl's dream. # Papa caught her up ...
3050    hand and placed it on Raquel's lips. He could ...
Name: clean_text, Length: 3051, dtype: object
0      , which we can not make to God. When our spiri...
1      the occupants. # Even the local section of the...
2      , yeah. It's hard to find the part where you'r...
3      , Houston had no layoffs or furloughs. As the ...
4      It works every time -- even on Chris Christie,...
                             ...
891    Parade All-American in football and a state ch...
892    to campaign against you. RON CLAIBORNE: voice-...
893    " oil on canvas. / Chuck Close 51919 # The Uni...
894    local and government views. " In Colombia, Fos...
895    the lone Oscar citation for The Hurricane, whi...
Name: clean_text, Length: 896, dtype: object

In [175]:
def distance_from_lemma(group):
    indices = group.index[group['is_target']].tolist()
    if not indices:
        group['distance_from_target'] = None
        return group
    first_index = indices[0]
    group['distance_from_target'] = (group.index.to_numpy() - first_index).astype(int).tolist()
    return group

target_lemma = "burn"
# framebert_df['is_target'] = framebert_df['Token_lemma'] == target_lemma
#
# framebert_df = framebert_df.groupby("Article").apply(distance_from_lemma)
# framebert_df = framebert_df.rename(columns={"Article": "Article_col"})

ffb['is_target'] = ffb['Token_lemma'] == target_lemma
ffb = ffb.groupby("Article").apply(distance_from_lemma)
ffb = ffb.rename(columns={"Article": "Article_col"})

"""TODO need to figure out how to make it work with non-burn targets"""

C:\Users\micah\AppData\Local\Temp\ipykernel_8608\3075259160.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ffb = ffb.groupby("Article").apply(distance_from_lemma)

In [52]:
framebert_df

              Article  Sentence         Tokens  Borderline_metaphor  \
Article
0       0           0         0              a                    0
        1           0         0        meaning                    0
        2           0         0             to                    1
        3           0         0           this                    1
        4           0         0  manifestation                    0
...               ...       ...            ...                  ...
311     9576      311         1              .                    0
        9577      311         2              #                    0
        9578      311         2         Though                    0
        9579      311         2          still                    0
        9580      311         2       commonly                    0

              Real_metaphors                 Frame_label    Token_lemma  \
Article
0       0                  0                           _              a
        1                  0                           _           mean
        2                  0                           _             to
        3                  0                           _           this
        4                  0                        Sign  manifestation
...                      ...                         ...            ...
311     9576               0                           _              .
        9577               0                           _              #
        9578               0                  Concessive         though
        9579               0  Continued_state_of_affairs          still
        9580               0                           _       commonly

              is_target distance_from_target
Article
0       0         False                  -15
        1         False                  -14
        2         False                  -13
        3         False                  -12
        4         False                  -11
...                 ...                  ...
311     9576      False                   11
        9577      False                   12
        9578      False                   13
        9579      False                   14
        9580      False                   15

[9581 rows x 9 columns]

In [53]:
framebert_df.groupby("Frame_label")["distance_from_target"].mean()

Frame_label
Abandonment             -7.5
Abounding_with         0.875
Accompaniment       2.166667
Accoutrements      -8.142857
Activity_ongoing         2.8
                      ...
Wearing                -14.0
Weather                 -4.0
Willingness             13.0
Work                    10.0
_                   0.404863
Name: distance_from_target, Length: 373, dtype: object

In [60]:
framebert_df[framebert_df["Borderline_metaphor"] == 1].distance_from_target.mean()

0.5414908579465542

In [61]:
framebert_df[framebert_df["Real_metaphors"] == 1].distance_from_target.mean()

0.2926829268292683

In [73]:
avg_distance_borderline_frame = (
    framebert_df[framebert_df['Borderline_metaphor'] == 1]
    .groupby('Frame_label')['distance_from_target']
    .mean()
)

avg_distance_borderline_frame

Frame_label
Abounding_with                  5.0
Activity_resume                -8.0
Activity_stop                 -14.0
Adopt_selection               -13.0
Aesthetics                     13.0
                             ...
Transition_to_a_quality        13.0
Transition_to_state       -5.333333
Turning_out                   -13.5
Type                           13.0
_                          1.055409
Name: distance_from_target, Length: 150, dtype: object

In [71]:
avg_distance_real_frame = (
    framebert_df[framebert_df['Real_metaphors'] == 1]
    .groupby('Frame_label')['distance_from_target']
    .mean()
)

avg_distance_real_frame

Frame_label
Abounding_with       1.5
Activity_resume     -8.0
Adopt_selection    -13.0
Aesthetics          13.0
Assessing            6.0
                   ...
Taking_time         -1.0
Theft               10.0
Topic              -11.0
Toxic_substance     13.0
_                  0.864
Name: distance_from_target, Length: 69, dtype: object

In [80]:
avg_distance_nonmet_frame = (
    framebert_df[(framebert_df['Borderline_metaphor'] == 0) & (framebert_df['Real_metaphors'] == 0)]
    .groupby('Frame_label')['distance_from_target']
    .mean()
)

avg_distance_nonmet_frame

Frame_label
Abandonment             -7.5
Abounding_with         -3.25
Accompaniment       2.166667
Accoutrements      -8.142857
Activity_ongoing         2.8
                      ...
Wearing                -14.0
Weather                 -4.0
Willingness             13.0
Work                    10.0
_                   0.317073
Name: distance_from_target, Length: 339, dtype: object

In [74]:
framebert_df[framebert_df['distance_from_target'] == 2].Frame_label.value_counts()

Frame_label
Experiencer_focus          135
Emotion_directed            83
_                           41
Desiring                    24
Judgment                     3
Needing                      3
Certainty                    3
Fear                         3
Personal_relationship        2
Medical_conditions           2
Reasoning                    1
Body_parts                   1
Fire_burning                 1
Awareness                    1
Expectation                  1
Likelihood                   1
Opinion                      1
Importance                   1
Purpose                      1
Becoming_aware               1
Judgment_direct_address      1
Name: count, dtype: int64

In [78]:
framebert_df[(framebert_df.Frame_label == "Experiencer_focus") & (framebert_df.distance_from_target == 2)].Token_lemma.value_counts()

Token_lemma
shame            29
embarrassment    23
jealousy         10
hatred           10
love              8
curiosity         7
humiliation       7
hate              6
lust              5
envy              4
guilt             3
resentment        3
passion           2
pride             2
compassion        2
love/             2
horror            1
nervousness       1
pity              1
discomfort        1
ardor             1
satisfaction      1
regret            1
relish            1
impatience        1
agony             1
animosity         1
ecstasy           1
Name: count, dtype: int64

In [79]:
framebert_df[(framebert_df.Frame_label == "Emotion_directed") & (framebert_df.distance_from_target == 2)].Token_lemma.value_counts()

Token_lemma
anger             24
rage              12
indignation        7
fury               7
excitement         5
frustration        4
shame              4
impatience         3
worry              3
anguish            3
annoyance          2
grief              2
agony              1
disappointment     1
anxiety            1
outrage            1
sorrow             1
surprise           1
irritation         1
Name: count, dtype: int64

In [82]:
framebert_df

              Article_col  Sentence         Tokens  Borderline_metaphor  \
Article
0       0               0         0              a                    0
        1               0         0        meaning                    0
        2               0         0             to                    1
        3               0         0           this                    1
        4               0         0  manifestation                    0
...                   ...       ...            ...                  ...
311     9576          311         1              .                    0
        9577          311         2              #                    0
        9578          311         2         Though                    0
        9579          311         2          still                    0
        9580          311         2       commonly                    0

              Real_metaphors                 Frame_label    Token_lemma  \
Article
0       0                  0                           _              a
        1                  0                           _           mean
        2                  0                           _             to
        3                  0                           _           this
        4                  0                        Sign  manifestation
...                      ...                         ...            ...
311     9576               0                           _              .
        9577               0                           _              #
        9578               0                  Concessive         though
        9579               0  Continued_state_of_affairs          still
        9580               0                           _       commonly

              is_target distance_from_target
Article
0       0         False                  -15
        1         False                  -14
        2         False                  -13
        3         False                  -12
        4         False                  -11
...                 ...                  ...
311     9576      False                   11
        9577      False                   12
        9578      False                   13
        9579      False                   14
        9580      False                   15

[9581 rows x 9 columns]

In [87]:
framebert_df[(framebert_df["Real_metaphors"] == 1) & (framebert_df["distance_from_target"] != 0) & (framebert_df["distance_from_target"] != 2)]

              Article_col  Sentence     Tokens  Borderline_metaphor  \
Article
3       103             3         0   famished                    1
        113             3         0     hollow                    1
        115             3         0       lazy                    1
        123             3         0  devouring                    1
4       129             4         1       dust                    1
...                   ...       ...        ...                  ...
308     9485          308         1    central                    1
309     9493          309         0   humblest                    1
310     9521          310         0       fast                    1
        9538          310         0    flashes                    1
        9540          310         0    ignites                    1

              Real_metaphors        Frame_label Token_lemma  is_target  \
Article
3       103                1    Biological_urge    famished      False
        113                1                  _      hollow      False
        115                1                  _        lazy      False
        123                1          Ingestion      devour      False
4       129                1                  _        dust      False
...                      ...                ...         ...        ...
308     9485               1                  _     central      False
309     9493               1                  _      humble      False
310     9521               1  Speed_description        fast      False
        9538               1    Moving_in_place       flash      False
        9540               1       Setting_fire      ignite      False

             distance_from_target
Article
3       103                    -5
        113                     5
        115                     7
        123                    15
4       129                   -10
...                           ...
308     9485                   11
309     9493                  -12
310     9521                  -13
        9538                    4
        9540                    6

[226 rows x 9 columns]

In [94]:
framebert_df[(framebert_df["Borderline_metaphor"] == 1) & (framebert_df["distance_from_target"] != 0) & (framebert_df["distance_from_target"] != 2)]

              Article_col  Sentence   Tokens  Borderline_metaphor  \
Article
0       2               0         0       to                    1
        3               0         0     this                    1
        16              0         1     with                    1
        22              0         1       to                    1
1       47              1         1     with                    1
...                   ...       ...      ...                  ...
310     9538          310         0  flashes                    1
        9540          310         0  ignites                    1
        9541          310         0  between                    1
311     9566          311         1     from                    1
        9568          311         1     with                    1

              Real_metaphors                Frame_label Token_lemma  \
Article
0       2                  0                          _          to
        3                  0                          _        this
        16                 0                          _        with
        22                 0                          _          to
1       47                 0                          _        with
...                      ...                        ...         ...
310     9538               1            Moving_in_place       flash
        9540               1               Setting_fire      ignite
        9541               0  Interior_profile_relation     between
311     9566               0                          _        from
        9568               0                          _        with

              is_target distance_from_target
Article
0       2         False                  -13
        3         False                  -12
        16        False                    1
        22        False                    7
1       47        False                    1
...                 ...                  ...
310     9538      False                    4
        9540      False                    6
        9541      False                    7
311     9566      False                    1
        9568      False                    3

[1121 rows x 9 columns]

In [98]:
fb = framebert_df

              Article_col  Sentence     Tokens  Borderline_metaphor  \
Article
0       10              0         1     Polish                    0
        11              0         1  violinist                    0
        12              0         1          ,                    0
        13              0         1        who                    0
        14              0         1        was                    0
...                   ...       ...        ...                  ...
311     9560          311         1         he                    0
        9561          311         1        did                    0
        9562          311         1        n't                    0
        9563          311         1      crash                    0
        9564          311         1        and                    0

              Real_metaphors Frame_label Token_lemma  is_target  \
Article
0       10                 0      Origin      polish      False
        11                 0           _   violinist      False
        12                 0           _           ,      False
        13                 0           _         who      False
        14                 0           _          be      False
...                      ...         ...         ...        ...
311     9560               0           _          he      False
        9561               0           _          do      False
        9562               0           _         not      False
        9563               0           _       crash      False
        9564               0           _         and      False

             distance_from_target
Article
0       10                     -5
        11                     -4
        12                     -3
        13                     -2
        14                     -1
...                           ...
311     9560                   -5
        9561                   -4
        9562                   -3
        9563                   -2
        9564                   -1

[1539 rows x 9 columns]

In [102]:
range_tuples = [(30, 25), (25, 20), (20, 15), (15, 10), (10, 3), (0, -5), (-5, -10), (-10, -15), (-15, -20)]
for i in range_tuples:
    print(i)
    print(
        fb[(fb['distance_from_target'] < i[0]) & (fb['distance_from_target'] >= i[1])].Frame_label.value_counts()

    )
fb[(fb['distance_from_target'] < 0) & (fb['distance_from_target'] >= -5)]

(30, 25)
Frame_label
_                            13
Interior_profile_relation     1
Name: count, dtype: int64
(25, 20)
Frame_label
_                             19
Emotion_directed               2
Attempt                        1
Duration_description           1
Fire_burning                   1
Abounding_with                 1
Desiring                       1
Continued_state_of_affairs     1
Name: count, dtype: int64
(20, 15)
Frame_label
_                             230
Motion                          5
Perception_experience           4
Capability                      4
Experiencer_focus               4
Intentionally_act               3
Body_parts                      3
People                          3
Age                             2
Give_impression                 2
Self_motion                     2
Desirability                    2
Calendric_unit                  2
Temporal_collocation            2
Emotion_directed                2
Being_employed                  2
Memory                          2
Giving                          2
Correctness                     2
Using                           2
Preventing_or_letting           1
Receiving                       1
Building_subparts               1
Desirable_event                 1
Opinion                         1
Perception_active               1
Color                           1
Speed_description               1
Connecting_architecture         1
Objective_influence             1
Evidence                        1
Proportion                      1
Locative_relation               1
Continued_state_of_affairs      1
Substance                       1
Fire_burning                    1
Manipulation                    1
Project                         1
Animals                         1
Fullness                        1
Ingestion                       1
Motion_directional              1
Cause_motion                    1
Simple_name                     1
Resolve_problem                 1
Hostile_encounter               1
Similarity                      1
Means                           1
Kinship                         1
Make_noise                      1
Daring                          1
Attack                          1
Departing                       1
Quantity                        1
Interior_profile_relation       1
Quantified_mass                 1
Cogitation                      1
Assistance                      1
Name: count, dtype: int64
(15, 10)
Frame_label
_                        1101
Experiencer_focus          13
Body_parts                 12
Temporal_collocation       12
People                     11
                         ...
Choosing                    1
Measure_duration            1
Finish_competition          1
Forming_relationships       1
Member_of_military          1
Name: count, Length: 199, dtype: int64
(10, 3)
Frame_label
_                    1558
Experiencer_focus      36
Body_parts             22
Emotion_directed       19
Time_vector            13
                     ...
Scrutiny                1
Membership              1
Spatial_contact         1
Rite                    1
Setting_fire            1
Name: count, Length: 200, dtype: int64
(0, -5)
Frame_label
_                       1073
Body_parts               110
Temporal_collocation      12
Experiencer_focus         12
Causation                 11
                        ...
Escaping                   1
Natural_features           1
Usefulness                 1
Posture                    1
Desirable_event            1
Name: count, Length: 143, dtype: int64
(-5, -10)
Frame_label
_                          1001
Body_parts                   19
Experiencer_focus            12
Perception_experience        11
Perception_active            11
                           ...
Expensiveness                 1
Cause_to_end                  1
Posture                       1
Evaluative_comparison         1
Surrendering_possession       1
Name: count, Length: 208, dtype: int64
(-10, -15)
Frame_label
_                    1006
Body_parts             17
People                 16
Calendric_unit         10
Age                     9
                     ...
Grasp                   1
Stimulus_focus          1
Activity_ongoing        1
Opinion                 1
Speed_description       1
Name: count, Length: 188, dtype: int64
(-15, -20)
Frame_label
_                    9
Becoming_a_member    1
Self_motion          1
Existence            1
Political_locales    1
Name: count, dtype: int64

              Article_col  Sentence     Tokens  Borderline_metaphor  \
Article
0       10              0         1     Polish                    0
        11              0         1  violinist                    0
        12              0         1          ,                    0
        13              0         1        who                    0
        14              0         1        was                    0
...                   ...       ...        ...                  ...
311     9560          311         1         he                    0
        9561          311         1        did                    0
        9562          311         1        n't                    0
        9563          311         1      crash                    0
        9564          311         1        and                    0

              Real_metaphors Frame_label Token_lemma  is_target  \
Article
0       10                 0      Origin      polish      False
        11                 0           _   violinist      False
        12                 0           _           ,      False
        13                 0           _         who      False
        14                 0           _          be      False
...                      ...         ...         ...        ...
311     9560               0           _          he      False
        9561               0           _          do      False
        9562               0           _         not      False
        9563               0           _       crash      False
        9564               0           _         and      False

             distance_from_target
Article
0       10                     -5
        11                     -4
        12                     -3
        13                     -2
        14                     -1
...                           ...
311     9560                   -5
        9561                   -4
        9562                   -3
        9563                   -2
        9564                   -1

[1539 rows x 9 columns]

In [157]:
range_tuples = [(30, 22), (22, 17), (17, 12), (12, 7), (7, 3), (0, -5), (-5, -10), (-10, -15), (-15, -20)]
results = []

for start, end in range_tuples:
    subset = fb[(fb['distance_from_target'] < start) & (fb['distance_from_target'] >= end)]

    # per-article presence of metaphors
    has_metaphor = subset.groupby('Article_col')['Real_metaphors'].any()
    has_borderline = subset.groupby('Article_col')['Borderline_metaphor'].any()

    count_with_metaphor = has_metaphor.sum()
    count_with_borderline = has_borderline.sum()

    total = has_metaphor.shape[0]

    # rates
    rate_real = count_with_metaphor / total if total > 0 else 0
    rate_borderline = count_with_borderline / total if total > 0 else 0
    rate_total = (count_with_metaphor + count_with_borderline) / total if total > 0 else 0

    results.append({
        'interval': f"{start} to {end}",
        'count_with_metaphor': count_with_metaphor,
        'count_with_borderline': count_with_borderline,
        'total_sentences': total,
        'rate_real': rate_real,
        'rate_borderline': rate_borderline,
        'rate_total': rate_total
    })

df_results = pd.DataFrame(results)
df_results

,interval,count_with_metaphor,count_with_borderline,total_sentences,rate_real,rate_borderline,rate_total
0,30 to 22,2,3,5,0.400000,0.600000,1.000000
1,22 to 17,0,4,12,0.000000,0.333333,0.333333
2,17 to 12,32,90,309,0.103560,0.291262,0.394822
3,12 to 7,40,124,310,0.129032,0.400000,0.529032
4,7 to 3,32,100,310,0.103226,0.322581,0.425806
5,0 to -5,29,96,310,0.093548,0.309677,0.403226
6,-5 to -10,40,124,304,0.131579,0.407895,0.539474
7,-10 to -15,35,106,303,0.115512,0.349835,0.465347
8,-15 to -20,0,1,7,0.000000,0.142857,0.142857

In [197]:
import string
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

# Filter rows in your interval
subset = fb[(-5 <= fb.distance_from_target) & (fb.distance_from_target < 0)]

# Keep only tokens that are not stopwords and are alphabetic
filtered_tokens = subset[
    ~subset['Tokens'].str.lower().isin(stop_words) &
    subset['Tokens'].str.isalpha()
]['Tokens']

# Get value counts
filtered_tokens.value_counts()

Tokens
eyes        35
face        22
cheeks      16
felt         7
heart        6
            ..
skeleton     1
living       1
Alchylus     1
ready        1
crash        1
Name: count, Length: 423, dtype: int64

In [198]:
import string
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

# Filter rows in your interval
subset = fb[(3 <= fb.distance_from_target) & (fb.distance_from_target < 10)]

# Keep only tokens that are not stopwords and are alphabetic
filtered_tokens = subset[
    ~subset['Tokens'].str.lower().isin(stop_words) &
    subset['Tokens'].str.isalpha()
]['Tokens']

# Get value counts
filtered_tokens.value_counts()

Tokens
would      6
burns      6
love       5
one        5
anger      5
          ..
came       1
prayed     1
hoplite    1
Damned     1
ragged     1
Name: count, Length: 632, dtype: int64

In [137]:
fb[~fb.distance_from_target.isin([0, 1, 2])].groupby("Article_col")[["Borderline_metaphor", "Real_metaphors"]].value_counts()

Article_col  Borderline_metaphor  Real_metaphors
0            0                    0                 25
             1                    0                  3
1            0                    0                 27
             1                    0                  1
2            0                    0                 27
                                                    ..
310          0                    0                 20
             1                    0                  3
                                  1                  3
311          0                    0                 27
             1                    0                  1
Name: count, Length: 705, dtype: int64

In [138]:
# Exclude target tokens
subset = fb[~fb.distance_from_target.isin([0, 1, 2])]

# Aggregate per article: check if there is any token with Borderline/Real metaphor
agg = subset.groupby("Article_col").agg({
    "Borderline_metaphor": "max",  # 1 if any token in article is borderline
    "Real_metaphors": "max"        # 1 if any token in article is real metaphor
}).reset_index()

# Count combinations of 0/0, 0/1, 1/0, 1/1
comb_counts = agg.groupby(["Borderline_metaphor", "Real_metaphors"]).size().reset_index(name="count")

print(comb_counts)

   Borderline_metaphor  Real_metaphors  count
0                    0               0     42
1                    1               0    124
2                    1               1    146

In [145]:
before = fb[(~fb.distance_from_target.isin([0,1,2])) & (fb.distance_from_target < 0)]
after = fb[(~fb.distance_from_target.isin([0,1,2])) & (fb.distance_from_target > 2)]

In [153]:
before.Real_metaphors.mean()

0.024762325889896086

In [152]:
after.Real_metaphors.mean()

0.027545499262174127

In [154]:
before.Frame_label.value_counts()

Frame_label
_                          3089
Body_parts                  146
People                       37
Temporal_collocation         30
Experiencer_focus            29
                           ...
Wearing                       1
Have_associated               1
Noise_makers                  1
Deserving                     1
Surrendering_possession       1
Name: count, Length: 302, dtype: int64

In [155]:
after.Frame_label.value_counts()

Frame_label
_                            2921
Experiencer_focus              53
Body_parts                     37
Emotion_directed               28
People                         27
                             ...
Practice                        1
Quantity                        1
Make_cognitive_connection       1
Avoiding                        1
Member_of_military              1
Name: count, Length: 287, dtype: int64

In [156]:
after[after.Frame_label == "Experiencer_focus"]

              Article_col  Sentence       Tokens  Borderline_metaphor  \
Article
0       30              0         1    happiness                    0
7       235             7         1       Lament                    0
        241             7         1         Love                    0
11      364            11         1      passion                    1
13      421            13         0         love                    0
27      846            27         1         lust                    0
33      1035           33         3        sorry                    0
52      1617           52         2       hatred                    0
67      2078           67         2        sorry                    0
70      2166           70         1        shame                    0
77      2381           77         1         fear                    0
        2384           77         1         lust                    0
89      2755           89         0        pined                    0
91      2820           91         2         love                    0
94      2909           94         3       feared                    0
100     3092          100         2        pride                    0
140     4307          140         1  enthusiasm.                    0
141     4337          141         1   enthusiasm                    0
142     4366          142         0     patience                    0
        4369          142         0       hunger                    0
144     4425          144         1     jealousy                    0
        4430          144         1    cherished                    0
148     4546          148         3     despises                    0
172     5281          172         1         hate                    0
174     5332          174         0        shame                    0
189     5795          189         1       regret                    0
194     5946          194         1  humiliation                    0
206     6314          206         1         love                    0
        6318          206         1  fulfillment                    0
        6320          206         1    happiness                    0
214     6572          214         1        loved                    0
225     6903          225         2         pain                    0
243     7463          243         2         Love                    0
        7466          243         2         hate                    0
        7472          243         3         love                    0
244     7490          244         1         Love                    0
        7493          244         1         hate                    0
        7499          244         2         love                    0
248     7621          248         1        guilt                    0
        7624          248         1      remorse                    0
252     7755          252         1         love                    0
253     7776          253         1        shame                    0
261     8020          261         0        pride                    0
264     8115          264         0      shyness                    0
268     8246          268         2         LOVE                    0
273     8392          273         4   impatience                    0
275     8448          275         1         envy                    0
        8454          275         1        shame                    0
277     8530          277         2        hated                    0
285     8766          285         1       hatred                    0
298     9175          298         1        loves                    0
299     9197          299         1         envy                    0
        9203          299         1        shame                    0

              Real_metaphors        Frame_label  Token_lemma  is_target  \
Article
0       30                 0  Experiencer_focus    happiness      False
7       235                0  Experiencer_focus       lament      False
        241                0  Experiencer_focus         love      False
11      364                1  Experiencer_focus      passion      False
13      421                0  Experiencer_focus         love      False
27      846                0  Experiencer_focus         lust      False
33      1035               0  Experiencer_focus        sorry      False
52      1617               0  Experiencer_focus       hatred      False
67      2078               0  Experiencer_focus        sorry      False
70      2166               0  Experiencer_focus        shame      False
77      2381               0  Experiencer_focus         fear      False
        2384               0  Experiencer_focus         lust      False
89      2755               0  Experiencer_focus         pine      False
91      2820               0  Experiencer_focus         love      False
94      2909               0  Experiencer_focus         fear      False
100     3092               0  Experiencer_focus        pride      False
140     4307               0  Experiencer_focus   enthusiasm      False
141     4337               0  Experiencer_focus   enthusiasm      False
142     4366               0  Experiencer_focus     patience      False
        4369               0  Experiencer_focus       hunger      False
144     4425               0  Experiencer_focus     jealousy      False
        4430               0  Experiencer_focus      cherish      False
148     4546               0  Experiencer_focus      despise      False
172     5281               0  Experiencer_focus         hate      False
174     5332               0  Experiencer_focus        shame      False
189     5795               0  Experiencer_focus       regret      False
194     5946               0  Experiencer_focus  humiliation      False
206     6314               0  Experiencer_focus         love      False
        6318               0  Experiencer_focus  fulfillment      False
        6320               0  Experiencer_focus    happiness      False
214     6572               0  Experiencer_focus         love      False
225     6903               0  Experiencer_focus         pain      False
243     7463               0  Experiencer_focus         love      False
        7466               0  Experiencer_focus         hate      False
        7472               0  Experiencer_focus         love      False
244     7490               0  Experiencer_focus         love      False
        7493               0  Experiencer_focus         hate      False
        7499               0  Experiencer_focus         love      False
248     7621               0  Experiencer_focus        guilt      False
        7624               0  Experiencer_focus      remorse      False
252     7755               0  Experiencer_focus         love      False
253     7776               0  Experiencer_focus        shame      False
261     8020               0  Experiencer_focus        pride      False
264     8115               0  Experiencer_focus      shyness      False
268     8246               0  Experiencer_focus         love      False
273     8392               0  Experiencer_focus   impatience      False
275     8448               0  Experiencer_focus         envy      False
        8454               0  Experiencer_focus        shame      False
277     8530               0  Experiencer_focus         hate      False
285     8766               0  Experiencer_focus       hatred      False
298     9175               0  Experiencer_focus         love      False
299     9197               0  Experiencer_focus         envy      False
        9203               0  Experiencer_focus        shame      False

             distance_from_target
Article
0       30                     15
7       235                     4
        241                    10
11      364                     9
13      421                     4
27      846                    13
33      1035                    8
52      1617                    6
67      2078                    6
70      2166                    4
77      2381                    4
        2384                    7
89      2755                    8
91      2820                   12
94      2909                   10
100     3092                    9
140     4307                    6
141     4337                    6
142     4366                    4
        4369                    7
144     4425                    4
        4430                    9
148     4546                    5
172     5281                   15
174     5332                    4
189     5795                    4
194     5946                    4
206     6314                    4
        6318                    8
        6320                   10
214     6572                   15
225     6903                    6
243     7463                    3
        7466                    6
        7472                   12
244     7490                    3
        7493                    6
        7499                   12
248     7621                    4
        7624                    7
252     7755                   14
253     7776                    4
261     8020                    4
264     8115                    4
268     8246                   10
273     8392                    4
275     8448                    8
        8454                   14
277     8530                   14
285     8766                    4
298     9175                   11
299     9197                   12
        9203                   18

In [161]:
from scipy.stats import chi2_contingency

In [187]:
### literal analysis
range_tuples = [(30, 22), (22, 17), (17, 12), (12, 7), (7, 3), (0, -5), (-5, -10), (-10, -15), (-15, -20)]
results = []

for start, end in range_tuples:
    subset = ffb[(ffb['distance_from_target'] < start) & (ffb['distance_from_target'] >= end)]

    # per-article presence of metaphors
    has_metaphor = subset.groupby('Article_col')['Real_metaphors'].any()
    has_borderline = subset.groupby('Article_col')['Borderline_metaphor'].any()

    count_with_metaphor = has_metaphor.sum()
    count_with_borderline = has_borderline.sum()

    total = has_metaphor.shape[0]

    # rates
    rate_real = count_with_metaphor / total if total > 0 else 0
    rate_borderline = count_with_borderline / total if total > 0 else 0
    rate_total = (count_with_metaphor + count_with_borderline) / total if total > 0 else 0

    results.append({
        'interval': f"{start} to {end}",
        'count_with_metaphor': count_with_metaphor,
        'count_with_borderline': count_with_borderline,
        'total_sentences': total,
        'rate_real': rate_real,
        'rate_borderline': rate_borderline,
        'rate_total': rate_total
    })

df_results = pd.DataFrame(results)
df_results

,interval,count_with_metaphor,count_with_borderline,total_sentences,rate_real,rate_borderline,rate_total
0,30 to 22,1,1,1,1.000000,1.000000,2.000000
1,22 to 17,0,0,1,0.000000,0.000000,0.000000
2,17 to 12,8,23,77,0.103896,0.298701,0.402597
3,12 to 7,11,26,77,0.142857,0.337662,0.480519
4,7 to 3,9,17,77,0.116883,0.220779,0.337662
5,0 to -5,6,15,77,0.077922,0.194805,0.272727
6,-5 to -10,9,26,76,0.118421,0.342105,0.460526
7,-10 to -15,4,16,76,0.052632,0.210526,0.263158
8,-15 to -20,0,0,0,0.000000,0.000000,0.000000

In [196]:
# articles where the target sentence (distance = 0) has a real metaphor
excluded_articles = set(
    ffb.loc[
        (ffb['distance_from_target'] == 0) &
        (ffb['Real_metaphors'] == 1),
        'Article_col'
    ]
)
excluded_articles

range_tuples = [(30, 22), (22, 17), (17, 12), (12, 7), (7, 3), (0, -5), (-5, -10), (-10, -15), (-15, -20)]
results = []

for start, end in range_tuples:

    # interval subset
    subset = ffb[
        (ffb['distance_from_target'] < start) &
        (ffb['distance_from_target'] >= end)
    ]

    # exclude unwanted articles
    subset = subset[~subset['Article_col'].isin(excluded_articles)]

    # per-article presence of metaphors
    has_metaphor = subset.groupby('Article_col')['Real_metaphors'].any()
    has_borderline = subset.groupby('Article_col')['Borderline_metaphor'].any()

    count_with_metaphor = has_metaphor.sum()
    count_with_borderline = has_borderline.sum()

    total = has_metaphor.shape[0]

    # rates
    rate_real = count_with_metaphor / total if total > 0 else 0
    rate_borderline = count_with_borderline / total if total > 0 else 0
    rate_total = (count_with_metaphor + count_with_borderline) / total if total > 0 else 0

    results.append({
        'interval': f"{start} to {end}",
        'count_with_metaphor': count_with_metaphor,
        'count_with_borderline': count_with_borderline,
        'total_sentences': total,
        'rate_real': rate_real,
        'rate_borderline': rate_borderline,
        'rate_total': rate_total
    })

df_results = pd.DataFrame(results)
df_results

,interval,count_with_metaphor,count_with_borderline,total_sentences,rate_real,rate_borderline,rate_total
0,30 to 22,1,1,1,1.000000,1.000000,2.000000
1,22 to 17,0,0,1,0.000000,0.000000,0.000000
2,17 to 12,7,16,53,0.132075,0.301887,0.433962
3,12 to 7,5,13,53,0.094340,0.245283,0.339623
4,7 to 3,7,12,53,0.132075,0.226415,0.358491
5,0 to -5,2,9,53,0.037736,0.169811,0.207547
6,-5 to -10,7,14,52,0.134615,0.269231,0.403846
7,-10 to -15,3,11,52,0.057692,0.211538,0.269231
8,-15 to -20,0,0,0,0.000000,0.000000,0.000000

In [179]:
ffb[ffb.distance_from_target == 0].Real_metaphors.value_counts()

Real_metaphors
0    53
1    24
Name: count, dtype: int64

In [183]:
ffb[ffb.distance_from_target == 0].Borderline_metaphor.value_counts()

Borderline_metaphor
0    50
1    27
Name: count, dtype: int64

              Article_col  Sentence    Tokens  Borderline_metaphor  \
Article
2       61              2         0       She                    0
        62              2         0     never                    0
        63              2         0    sleeps                    0
        64              2         0      Only                    0
        65              2         0     roams                    0
...                   ...       ...       ...                  ...
66      2057           66         2      Cora                    0
        2058           66         2         ,                    0
        2059           66         2   hearing                    0
        2060           66         2       the                    0
        2061           66         2  sentence                    0

              Real_metaphors            Frame_label Token_lemma  is_target  \
Article
2       61                 0                      _         she      False
        62                 0              Frequency       never      False
        63                 0                  Sleep       sleep      False
        64                 0                      _        only      False
        65                 0            Self_motion        roam      False
...                      ...                    ...         ...        ...
66      2057               0                      _        Cora      False
        2058               0                      _           ,      False
        2059               0  Perception_experience        hear      False
        2060               0                      _         the      False
        2061               0                Revenge    sentence      False

              distance_from_target
Article
2       61                     -15
        62                     -14
        63                     -13
        64                     -12
        65                     -11
...                            ...
66      2057                    11
        2058                    12
        2059                    13
        2060                    14
        2061                    15

[741 rows x 9 columns]

In [182]:
real_0 = [3, 4, 6, 12, 21, 26, 28, 30, 33, 36, 38, 57, 62, 67, 79, 81, 98, 105, 107, 145, 148, 149, 158, 180, 192, 198, 200, 202, 211, 218, 232, 240, 255, 256, 261, 266, 273, 275, 277, 286, 299, 301, 308, 311]

fb[fb.Article_col.isin(real_0)]

              Article_col  Sentence    Tokens  Borderline_metaphor  \
Article
3       93              3         0        at                    1
        94              3         0       the                    0
        95              3         0      same                    0
        96              3         0      time                    0
        97              3         0  requires                    0
...                   ...       ...       ...                  ...
311     9576          311         1         .                    0
        9577          311         2         #                    0
        9578          311         2    Though                    0
        9579          311         2     still                    0
        9580          311         2  commonly                    0

              Real_metaphors                 Frame_label Token_lemma  \
Article
3       93                 0                           _          at
        94                 0                           _         the
        95                 0                Identicality        same
        96                 0                           _        time
        97                 0         Have_as_requirement     require
...                      ...                         ...         ...
311     9576               0                           _           .
        9577               0                           _           #
        9578               0                  Concessive      though
        9579               0  Continued_state_of_affairs       still
        9580               0                           _    commonly

              is_target distance_from_target
Article
3       93        False                  -15
        94        False                  -14
        95        False                  -13
        96        False                  -12
        97        False                  -11
...                 ...                  ...
311     9576      False                   11
        9577      False                   12
        9578      False                   13
        9579      False                   14
        9580      False                   15

[1355 rows x 9 columns]

In [204]:
e.to_csv("data/processed/emo.csv")
fb.to_csv("data/processed/burn.csv")
ffb.to_csv("data/processed/literal.csv")

In [1]:
### all emotion / heat data

import pandas as pd
e = pd.read_csv('data/processed/emo.csv')
range_tuples = [(30, 22), (22, 17), (17, 12), (12, 7), (7, 3), (0, -5), (-5, -10), (-10, -15), (-15, -20)]
results = []

for start, end in range_tuples:
    subset = e[(e['distance_from_target'] < start) & (e['distance_from_target'] >= end)]

    # per-article presence of metaphors
    has_metaphor = subset.groupby('Article_col')['Real_metaphors'].any()
    has_borderline = subset.groupby('Article_col')['Borderline_metaphor'].any()

    count_with_metaphor = has_metaphor.sum()
    count_with_borderline = has_borderline.sum()

    total = has_metaphor.shape[0]

    # rates
    rate_real = count_with_metaphor / total if total > 0 else 0
    rate_borderline = count_with_borderline / total if total > 0 else 0
    rate_total = (count_with_metaphor + count_with_borderline) / total if total > 0 else 0

    results.append({
        'interval': f"{start} to {end}",
        'count_with_metaphor': count_with_metaphor,
        'count_with_borderline': count_with_borderline,
        'total_sentences': total,
        'rate_real': rate_real,
        'rate_borderline': rate_borderline,
        'rate_total': rate_total
    })

df_results = pd.DataFrame(results)
df_results

KeyError: 'distance_from_target'

In [208]:
 e
 e

,Article,Sentence,Tokens,Borderline_metaphor,Real_metaphors,Frame_label,Token_lemma
0,0,0,was,0,0,_,be
1,0,0,tormented,1,1,Emotion_directed,torment
2,0,0,with,1,0,_,with
3,0,0,his,0,0,_,his
4,0,0,life,0,0,_,life
...,...,...,...,...,...,...,...
10284,333,2,of,0,0,Partitive,of
10285,333,2,your,0,0,_,your
10286,333,2,body,0,0,Body_parts,body
10287,333,2,.,0,0,_,.
10288,333,3,#,0,0,_,#